import 'package:flutter/material.dart';

/* Text Write a comment
    Autogenerated by FlutLab FTF Generator
  */
class WriteacommentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Write a comment''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 161, 161, 161),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
