import 'package:flutter/material.dart';

/* Text Topic to Study
    Autogenerated by FlutLab FTF Generator
  */
class TopictoStudyWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Topic to Study''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 14, 36, 220),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
