import 'package:flutter/material.dart';
import 'package:flutterapp/figma/logowidget/widgets/BLogo1Widget.dart';
import 'package:flutterapp/figma/logowidget/widgets/Rectangle1Widget.dart';
import 'package:flutterapp/figma/logowidget/widgets/BPrincipal1Widget.dart';
import 'package:flutterapp/figma/logowidget/widgets/CopyrightEvertixWidget.dart';
import 'package:flutterapp/figma/logowidget/widgets/TutoFastWidget.dart';

/* Frame Logo
    Autogenerated by FlutLab FTF Generator
  */
class LogoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefined0472'),
      child: Container(
        width: 375.0,
        height: 812.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Container(
                  width: null,
                  height: null,
                  decoration: BoxDecoration(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                  child: null,
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: BPrincipal1Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: Rectangle1Widget(),
                ),
                Positioned(
                  left: 91.0,
                  top: 639.0,
                  right: null,
                  bottom: null,
                  width: 193.0,
                  height: 61.0,
                  child: TutoFastWidget(),
                ),
                Positioned(
                  left: 81.0,
                  top: 268.0,
                  right: null,
                  bottom: null,
                  width: 198.0,
                  height: 195.15097045898438,
                  child: BLogo1Widget(),
                ),
                Positioned(
                  left: 118.0,
                  top: 701.0,
                  right: null,
                  bottom: null,
                  width: 138.0,
                  height: 18.0,
                  child: CopyrightEvertixWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
