import 'package:flutter/material.dart';

/* Text Book a class with a teacher who never shows up. That is why I want the hours of the reserved class to be returned to me or to be assigned another teacher urgently.
    Autogenerated by FlutLab FTF Generator
  */
class BookaclasswithateacherwhonevershowsupThatiswhyIwantthehoursofthereservedclasstobereturnedtomeortobeassignedanotherteacherurgentlyWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Book a class with a teacher who never shows up. That is why I want the hours of the reserved class to be returned to me or to be assigned another teacher urgently.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
