import 'package:flutter/material.dart';

/* Rectangle Rectangle 29
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle29Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(9.0),
      child: Container(
        width: 294.0,
        height: 101.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(9.0),
          border: Border.all(
            width: 2.0,
            color: Color.fromARGB(255, 229, 229, 229),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(9.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
