import 'package:flutter/material.dart';

/* Text Session Problems
    Autogenerated by FlutLab FTF Generator
  */
class SessionProblemsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Session Problems ''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 25.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
