import 'package:flutter/material.dart';

/* Text We take care of your problems 24/7
    Autogenerated by FlutLab FTF Generator
  */
class Wetakecareofyourproblems247Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''We take care of your problems 24/7''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
