import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/FP1Widget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle13Widget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle14Widget5.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/HoursWidget3.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/StartTimeWidget4.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle9Widget8.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle32Widget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Ellipse4Widget4.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/SecondWorldWarWidget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle12Widget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle29Widget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/FlutLab48MbWidget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/EnteryourSessionhereWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Line8Widget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/ClassWidget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/TWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/ClassDetailWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/FlutLab2Widget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/TopicWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/MarioSebastianWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/DL2Widget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/TeacherWidget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/RiveraSotomayorWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle10Widget8.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/FlutLab700Widget4.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/History_SecondWorldWarpptWidget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/ThisbuttonredirectsyoutothesessionofyourclassWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/BTH1Widget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/ResourcesWidget1.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/BTP1Widget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle17Widget5.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle18Widget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/HistoryWidget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/ClassHistoryWidget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/BTC1Widget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/FD1Widget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/History_ExamenWWIIdocWidget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Polygon5Widget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle16Widget7.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/DL1Widget.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/CourseWidget2.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/Rectangle8Widget9.dart';
import 'package:flutterapp/figma/studentresourceswidget/widgets/FlutLab64MbWidget.dart';

/* Frame Student Resources
    Autogenerated by FlutLab FTF Generator
  */
class StudentResourcesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 1.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget8(),
          ),
          Positioned(
            left: 24.0,
            top: 570.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget7(),
          ),
          Positioned(
            left: 45.0,
            top: 589.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget1(),
          ),
          Positioned(
            left: 45.0,
            top: 624.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget1(),
          ),
          Positioned(
            left: 135.0,
            top: 624.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 15.0,
            child: SecondWorldWarWidget2(),
          ),
          Positioned(
            left: 135.0,
            top: 654.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 15.0,
            child: HistoryWidget7(),
          ),
          Positioned(
            left: 135.0,
            top: 684.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget4(),
          ),
          Positioned(
            left: 45.0,
            top: 654.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget2(),
          ),
          Positioned(
            left: 45.0,
            top: 684.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget4(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget8(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget2(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget7(),
          ),
          Positioned(
            left: 241.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 17.0,
            child: ClassHistoryWidget2(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget9(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget7(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget7(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget7(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget7(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle14Widget5(),
          ),
          Positioned(
            left: 76.0,
            top: 260.0,
            right: null,
            bottom: null,
            width: 222.0,
            height: 25.0,
            child: EnteryourSessionhereWidget1(),
          ),
          Positioned(
            left: 53.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 271.0,
            height: 13.0,
            child: ThisbuttonredirectsyoutothesessionofyourclassWidget1(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget5(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget7(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget4(),
          ),
          Positioned(
            left: 129.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 117.0,
            height: 18.0,
            child: MarioSebastianWidget1(),
          ),
          Positioned(
            left: 105.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 166.0,
            height: 34.0,
            child: RiveraSotomayorWidget1(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget2(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: TWidget1(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget3(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: TeacherWidget2(),
          ),
          Positioned(
            left: 24.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 197.0,
            child: Rectangle29Widget2(),
          ),
          Positioned(
            left: 87.0,
            top: 479.0,
            right: null,
            bottom: null,
            width: 147.0,
            height: 15.0,
            child: History_ExamenWWIIdocWidget(),
          ),
          Positioned(
            left: 87.0,
            top: 496.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 16.0,
            child: FlutLab48MbWidget(),
          ),
          Positioned(
            left: 87.0,
            top: 403.0,
            right: null,
            bottom: null,
            width: 168.0,
            height: 15.0,
            child: History_SecondWorldWarpptWidget(),
          ),
          Positioned(
            left: 87.0,
            top: 420.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 16.0,
            child: FlutLab64MbWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 458.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line8Widget2(),
          ),
          Positioned(
            left: 24.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 38.0,
            child: Rectangle32Widget(),
          ),
          Positioned(
            left: 343.0,
            top: 372.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon5Widget2(),
          ),
          Positioned(
            left: 143.0,
            top: 349.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 30.0,
            child: ResourcesWidget1(),
          ),
          Positioned(
            left: 338.0,
            top: 432.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: DL1Widget(),
          ),
          Positioned(
            left: 338.0,
            top: 508.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: DL2Widget(),
          ),
          Positioned(
            left: 40.0,
            top: 402.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: FP1Widget(),
          ),
          Positioned(
            left: 41.0,
            top: 478.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: FD1Widget(),
          )
        ]),
      ),
    ));
  }
}
