import 'package:flutter/material.dart';

/* Text Assigned Date
    Autogenerated by FlutLab FTF Generator
  */
class AssignedDateWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Assigned Date''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 102, 250, 2),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
