import 'package:flutter/material.dart';

/* Text Reserve Successful
    Autogenerated by FlutLab FTF Generator
  */
class ReserveSuccessfulWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Reserve Successful''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 19.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 102, 250, 2),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
