import 'package:flutter/material.dart';

/* Text Thank you for trusting the TutoFast service, currently your reservation request has been sent to all available teachers who meet your requirements. Within 1 hour we will notify you of the list of teachers who accepted your application, remember that to choose the teacher you must go to the Agenda option.
    Autogenerated by FlutLab FTF Generator
  */
class ThankyoufortrustingtheTutoFastservicecurrentlyyourreservationrequesthasbeensenttoallavailableteacherc0f2d58a7e3f4cda9b95c1e7db17612f
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Thank you for trusting the TutoFast service, currently your reservation request has been sent to all available teachers who meet your requirements. Within 1 hour we will notify you of the list of teachers who accepted your application, remember that to choose the teacher you must go to the Agenda option.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
