import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/EQ3Widget.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/CourseWidget5.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle29Widget4.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/TeacherWidget4.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle10Widget11.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/FlutLab2Widget4.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/ArturoFelipeWidget1.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle9Widget11.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/StartTimeWidget6.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/LiteraryGenresWidget2.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle17Widget7.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/FlutLab900Widget3.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle16Widget10.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/TopicWidget3.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/BTP1Widget10.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/EQ2Widget.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/StatusWidget2.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/SendWidget3.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle8Widget12.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/FlutLab700Widget8.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/BTC1Widget10.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle25Widget4.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/EE5Widget1.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/ClassHistoryWidget5.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/TWidget3.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle13Widget10.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/TorresSalvatoreWidget1.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/ClassDetailWidget3.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/HoursWidget6.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle12Widget10.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/FinishedWidget2.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/EQ4Widget.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/EndTimeWidget2.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle30Widget2.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Rectangle18Widget10.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/EQ1Widget.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/BTH1Widget10.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/LiteratureWidget3.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/ExcellentteacherhecanlearnalotinhisclassverygoodteachingserviceIwillrecommendittomyfriendsWidget.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/Ellipse4Widget7.dart';
import 'package:flutterapp/figma/studentqualifywidget/widgets/ClassWidget5.dart';

/* Frame Student Qualify 
    Autogenerated by FlutLab FTF Generator
  */
class StudentQualifyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget11(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget11(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget5(),
          ),
          Positioned(
            left: 229.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget10(),
          ),
          Positioned(
            left: 241.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 17.0,
            child: ClassHistoryWidget5(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget12(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget10(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget10(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget10(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget10(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 198.0,
            child: Rectangle25Widget4(),
          ),
          Positioned(
            left: 43.0,
            top: 267.0,
            right: null,
            bottom: null,
            width: 290.0,
            height: 95.0,
            child: Rectangle29Widget4(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget7(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget10(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget7(),
          ),
          Positioned(
            left: 141.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 92.0,
            height: 18.0,
            child: ArturoFelipeWidget1(),
          ),
          Positioned(
            left: 107.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 162.0,
            height: 34.0,
            child: TorresSalvatoreWidget1(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget4(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: TWidget3(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget6(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: TeacherWidget4(),
          ),
          Positioned(
            left: 42.0,
            top: 405.0,
            right: null,
            bottom: null,
            width: 292.0,
            height: 26.0,
            child: Rectangle30Widget2(),
          ),
          Positioned(
            left: 250.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EE5Widget1(),
          ),
          Positioned(
            left: 54.0,
            top: 279.0,
            right: null,
            bottom: null,
            width: 267.0,
            height: 48.0,
            child:
                ExcellentteacherhecanlearnalotinhisclassverygoodteachingserviceIwillrecommendittomyfriendsWidget(),
          ),
          Positioned(
            left: 168.0,
            top: 409.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 18.0,
            child: SendWidget3(),
          ),
          Positioned(
            left: 24.0,
            top: 477.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget10(),
          ),
          Positioned(
            left: 45.0,
            top: 496.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget3(),
          ),
          Positioned(
            left: 45.0,
            top: 531.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget3(),
          ),
          Positioned(
            left: 135.0,
            top: 531.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 15.0,
            child: LiteraryGenresWidget2(),
          ),
          Positioned(
            left: 135.0,
            top: 561.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 15.0,
            child: LiteratureWidget3(),
          ),
          Positioned(
            left: 135.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget8(),
          ),
          Positioned(
            left: 135.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 15.0,
            child: FinishedWidget2(),
          ),
          Positioned(
            left: 137.0,
            top: 621.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab900Widget3(),
          ),
          Positioned(
            left: 45.0,
            top: 561.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget5(),
          ),
          Positioned(
            left: 45.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget6(),
          ),
          Positioned(
            left: 45.0,
            top: 621.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget2(),
          ),
          Positioned(
            left: 45.0,
            top: 651.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget2(),
          ),
          Positioned(
            left: 98.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EQ1Widget(),
          ),
          Positioned(
            left: 136.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EQ2Widget(),
          ),
          Positioned(
            left: 174.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EQ3Widget(),
          ),
          Positioned(
            left: 212.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EQ4Widget(),
          )
        ]),
      ),
    ));
  }
}
