import 'package:flutter/material.dart';

/* Text After add your Credit Card
    Autogenerated by FlutLab FTF Generator
  */
class AfteraddyourCreditCardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''After add your Credit Card''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
