import 'package:flutter/material.dart';

/* Text Banners and video advertising will be removed.
    Autogenerated by FlutLab FTF Generator
  */
class BannersandvideoadvertisingwillberemovedWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Banners and video advertising will be removed.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
