import 'package:flutter/material.dart';

/* Rectangle BS 1
    Autogenerated by FlutLab FTF Generator
  */
class BS1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 323.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/a1d2416cf8ecb9b84798aba293187aaf8cbaff7a.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/a1d2416cf8ecb9b84798aba293187aaf8cbaff7a.png",
          color: null,
          fit: BoxFit.cover,
          width: 375.0,
          height: 323.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
