import 'package:flutter/material.dart';

/* Text 30 days
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab30daysWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''30 days''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 15.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
