import 'package:flutter/material.dart';

/* Text Pay $30.00 per moth
    Autogenerated by FlutLab FTF Generator
  */
class Pay$3000permothWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Pay \$30.00 per moth''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
