import 'package:flutter/material.dart';

/* Text Try out the free trial of 7 days
    Autogenerated by FlutLab FTF Generator
  */
class Tryoutthefreetrialof7daysWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Try out the free trial of 7 days''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 136, 136, 136),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
