import 'package:flutter/material.dart';

/* Text You are given 2 hours as credits for the use of requesting a valid tutor within 7 days.
    Autogenerated by FlutLab FTF Generator
  */
class Youaregiven2hoursascreditsfortheuseofrequestingavalidtutorwithin7daysWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''You are given 2 hours as credits for the use of requesting a valid tutor within 7 days.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 10.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
