import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Rectangle 1
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 812.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 0L375 0L375 812L0 812L0 0Z')
          ..color = Color.fromARGB(130, 14, 36, 220),
      ]),
    );
  }
}
