import 'package:flutter/material.dart';

/* Text Email
    Autogenerated by FlutLab FTF Generator
  */
class EmailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Email''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 140, 140, 140),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
