import 'package:flutter/material.dart';

/* Rectangle MC 1
    Autogenerated by FlutLab FTF Generator
  */
class MC1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 423.0,
      height: 370.5035705566406,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/b44cdb26972559c2b389a37117951bebf9453e8b.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/b44cdb26972559c2b389a37117951bebf9453e8b.png",
          color: null,
          fit: BoxFit.cover,
          width: 423.0,
          height: 370.5035705566406,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
