import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* RegularPolygon Polygon 2
    Autogenerated by FlutLab FTF Generator
  */
class Polygon2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(0.00, -1.00, 0.00, 0.00, 1.00, 0.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 30.0,
          height: 30.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M12.4019 4.5C13.5566 2.5 16.4434 2.5 17.5981 4.5L25.3923 18C26.547 20 25.1036 22.5 22.7942 22.5L7.20577 22.5C4.89637 22.5 3.45299 20 4.6077 18L12.4019 4.5Z')
              ..color = Color.fromARGB(255, 14, 36, 220),
          ]),
        ));
  }
}
