import 'package:flutter/material.dart';

/* Text We need you to add your payment method to finish the selection process of your subscription.
    Autogenerated by FlutLab FTF Generator
  */
class WeneedyoutoaddyourpaymentmethodtofinishtheselectionprocessofyoursubscriptionWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''We need you to add your payment method to finish the selection process of your subscription.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
