import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/FlutLab7daystrialWidget1.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/AddressWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/ProfileWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/BirthdateWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/PabloGabrielWidget1.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/HoursWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/SubscriptionWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/SettingsWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/FlutLab241094Widget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/PersonalInformationWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle11Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Wetakecareofyourproblems247Widget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/ComplaintCenterWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/FlutLab76452369Widget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/BTC1Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/MjimenezgabrielhotmailcomWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/AvParacas452Widget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle13Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Ellipse4Widget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Yourcredittouseis2hoursWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/SurnamesWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/FreeWidget1.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/StudentWidget1.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle18Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle16Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/SWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/NamesWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/FlutLab2Widget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle9Widget4.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle17Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/DNIWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/EmailWidget1.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/MendezJimenezWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle10Widget4.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle12Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle14Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/PabloGabrielWidget.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/MendezJimenezWidget1.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/BTP1Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/BTH1Widget3.dart';
import 'package:flutterapp/figma/studentprofilewidget/widgets/Rectangle8Widget5.dart';

/* Frame Student Profile
    Autogenerated by FlutLab FTF Generator
  */
class StudentProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget4(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget4(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget5(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget3(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget3(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget3(),
          ),
          Positioned(
            left: 61.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget3(),
          ),
          Positioned(
            left: 45.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 41.0,
            height: 17.0,
            child: ProfileWidget(),
          ),
          Positioned(
            left: 13.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget3(),
          ),
          Positioned(
            left: 284.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 17.0,
            child: SettingsWidget(),
          ),
          Positioned(
            left: 147.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 17.0,
            child: SubscriptionWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 616.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 79.0,
            child: Rectangle11Widget3(),
          ),
          Positioned(
            left: 23.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 243.0,
            child: Rectangle16Widget3(),
          ),
          Positioned(
            left: 44.0,
            top: 362.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 20.0,
            child: PersonalInformationWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 57.0,
            height: 15.0,
            child: SurnamesWidget(),
          ),
          Positioned(
            left: 134.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 99.0,
            height: 15.0,
            child: MendezJimenezWidget(),
          ),
          Positioned(
            left: 134.0,
            top: 427.0,
            right: null,
            bottom: null,
            width: 81.0,
            height: 15.0,
            child: PabloGabrielWidget(),
          ),
          Positioned(
            left: 134.0,
            top: 457.0,
            right: null,
            bottom: null,
            width: 54.0,
            height: 15.0,
            child: FlutLab76452369Widget(),
          ),
          Positioned(
            left: 134.0,
            top: 544.0,
            right: null,
            bottom: null,
            width: 93.0,
            height: 15.0,
            child: AvParacas452Widget(),
          ),
          Positioned(
            left: 134.0,
            top: 513.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 15.0,
            child: FlutLab241094Widget(),
          ),
          Positioned(
            left: 134.0,
            top: 487.0,
            right: null,
            bottom: null,
            width: 184.0,
            height: 15.0,
            child: MjimenezgabrielhotmailcomWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 427.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: NamesWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 457.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 15.0,
            child: DNIWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 487.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: EmailWidget1(),
          ),
          Positioned(
            left: 44.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: BirthdateWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 547.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 15.0,
            child: AddressWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle14Widget3(),
          ),
          Positioned(
            left: 68.0,
            top: 257.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 49.0,
            child: FreeWidget1(),
          ),
          Positioned(
            left: 166.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 142.0,
            height: 13.0,
            child: Yourcredittouseis2hoursWidget(),
          ),
          Positioned(
            left: 166.0,
            top: 265.0,
            right: null,
            bottom: null,
            width: 79.0,
            height: 18.0,
            child: FlutLab7daystrialWidget1(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget3(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget3(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget(),
          ),
          Positioned(
            left: 137.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 101.0,
            height: 18.0,
            child: PabloGabrielWidget1(),
          ),
          Positioned(
            left: 116.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 34.0,
            child: MendezJimenezWidget1(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: SWidget(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: StudentWidget1(),
          ),
          Positioned(
            left: 93.0,
            top: 665.0,
            right: null,
            bottom: null,
            width: 191.0,
            height: 13.0,
            child: Wetakecareofyourproblems247Widget(),
          ),
          Positioned(
            left: 85.0,
            top: 629.0,
            right: null,
            bottom: null,
            width: 207.0,
            height: 42.0,
            child: ComplaintCenterWidget(),
          )
        ]),
      ),
    ));
  }
}
