import 'package:flutter/material.dart';

/* Rectangle BTC 1
    Autogenerated by FlutLab FTF Generator
  */
class BTC1Widget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 35.0,
      height: 35.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/d475b08f43a43ec52f690e901bdba92a7cc9ef4c.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/d475b08f43a43ec52f690e901bdba92a7cc9ef4c.png",
          color: null,
          fit: BoxFit.cover,
          width: 35.0,
          height: 35.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
