import 'package:flutter/material.dart';

/* Rectangle N2 1
    Autogenerated by FlutLab FTF Generator
  */
class N21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 28.81999969482422,
      height: 35.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/d53b3ae41a327266a8bb8cae00155523fb12677c.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/d53b3ae41a327266a8bb8cae00155523fb12677c.png",
          color: null,
          fit: BoxFit.cover,
          width: 28.81999969482422,
          height: 35.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
