import 'package:flutter/material.dart';

/* Text Enter the link of the virtual sesion, here
    Autogenerated by FlutLab FTF Generator
  */
class EnterthelinkofthevirtualsesionhereWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Enter the link of the virtual sesion, here''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 140, 140, 140),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
