import 'package:flutter/material.dart';

/* Text Physical
    Autogenerated by FlutLab FTF Generator
  */
class PhysicalWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Physical''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
