import 'package:flutter/material.dart';

/* Rectangle Rectangle 49
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle49Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(100.0),
      child: Container(
        width: 29.0,
        height: 27.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(100.0),
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 14, 36, 220),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(100.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 14, 36, 220),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
