import 'package:flutter/material.dart';

/* Rectangle Rectangle 23
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle23Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(11.0),
      child: Container(
        width: 302.0,
        height: 35.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(11.0),
          border: Border.all(
            width: 3.0,
            color: Color.fromARGB(255, 18, 204, 253),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(11.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(0, 255, 255, 255),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
