import 'package:flutter/material.dart';

/* Text Chemistry
    Autogenerated by FlutLab FTF Generator
  */
class ChemistryWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Chemistry''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 102, 250, 2),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
