import 'package:flutter/material.dart';

/* Text Classes, 2020
    Autogenerated by FlutLab FTF Generator
  */
class Classes2020Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Classes, 2020''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 15.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
