import 'package:flutter/material.dart';

/* Text Finished
    Autogenerated by FlutLab FTF Generator
  */
class FinishedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Finished''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 25.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 22, 80),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
