import 'package:flutter/material.dart';

/* Text 10/02
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab1002Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''10/02''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 1.171875,
        fontSize: 15.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
