import 'package:flutter/material.dart';

/* Text History
    Autogenerated by FlutLab FTF Generator
  */
class HistoryWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''History''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
