import 'package:flutter/material.dart';

/* Rectangle Rectangle 28
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle28Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 331.0,
        height: 43.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(12.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 22, 80),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
