import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle19Widget10.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle29Widget6.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle18Widget14.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle14Widget9.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Ellipse4Widget15.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle44Widget.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/CreateClassWidget1.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle12Widget19.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/StartTimeWidget10.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/CourseWidget8.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle16Widget19.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle17Widget12.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/FlutLab900Widget5.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/SecondWorldWarWidget4.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/StartClassWidget.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle9Widget20.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/MendezJimenezWidget4.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/ResourcesWidget2.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/HistoryWidget10.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/BTP1Widget19.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/BTH1Widget19.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/FlutLab2Widget8.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/StudentWidget2.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Httpsmrprofesorzoomus4578FG24DE58R63SF8Widget.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/FlutLab700Widget15.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/SWidget1.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle13Widget19.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/TopicWidget5.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle8Widget21.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/PabloGabrielWidget4.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/HoursWidget9.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Rectangle10Widget20.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/StatusWidget4.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/EndTimeWidget4.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/ClassWidget8.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/BTC1Widget19.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/ScheduleWidget2.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/SessionLinkWidget.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/ClassDetailWidget5.dart';
import 'package:flutterapp/figma/teacherclassdetailwidget/widgets/Polygon5Widget4.dart';

/* Frame Teacher Class Detail
    Autogenerated by FlutLab FTF Generator
  */
class TeacherClassDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget20(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget20(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget8(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget19(),
          ),
          Positioned(
            left: 239.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 17.0,
            child: CreateClassWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget21(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget19(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget19(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget19(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget19(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget12(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget14(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget15(),
          ),
          Positioned(
            left: 137.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 101.0,
            height: 18.0,
            child: PabloGabrielWidget4(),
          ),
          Positioned(
            left: 116.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 34.0,
            child: MendezJimenezWidget4(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget8(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: SWidget1(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget9(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: StudentWidget2(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle14Widget9(),
          ),
          Positioned(
            left: 131.0,
            top: 256.0,
            right: null,
            bottom: null,
            width: 114.0,
            height: 25.0,
            child: SessionLinkWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 288.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 26.0,
            child: Rectangle44Widget(),
          ),
          Positioned(
            left: 24.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 38.0,
            child: Rectangle29Widget6(),
          ),
          Positioned(
            left: 343.0,
            top: 372.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon5Widget4(),
          ),
          Positioned(
            left: 24.0,
            top: 654.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 31.0,
            child: Rectangle19Widget10(),
          ),
          Positioned(
            left: 147.0,
            top: 661.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 18.0,
            child: StartClassWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 411.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget19(),
          ),
          Positioned(
            left: 45.0,
            top: 430.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget5(),
          ),
          Positioned(
            left: 45.0,
            top: 465.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget5(),
          ),
          Positioned(
            left: 135.0,
            top: 465.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 15.0,
            child: SecondWorldWarWidget4(),
          ),
          Positioned(
            left: 135.0,
            top: 495.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 15.0,
            child: HistoryWidget10(),
          ),
          Positioned(
            left: 135.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget15(),
          ),
          Positioned(
            left: 134.0,
            top: 581.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 15.0,
            child: ScheduleWidget2(),
          ),
          Positioned(
            left: 134.0,
            top: 555.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab900Widget5(),
          ),
          Positioned(
            left: 45.0,
            top: 495.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget8(),
          ),
          Positioned(
            left: 45.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget10(),
          ),
          Positioned(
            left: 45.0,
            top: 555.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget4(),
          ),
          Positioned(
            left: 45.0,
            top: 585.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget4(),
          ),
          Positioned(
            left: 143.0,
            top: 349.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 30.0,
            child: ResourcesWidget2(),
          ),
          Positioned(
            left: 58.0,
            top: 293.0,
            right: null,
            bottom: null,
            width: 260.0,
            height: 13.0,
            child: Httpsmrprofesorzoomus4578FG24DE58R63SF8Widget(),
          )
        ]),
      ),
    ));
  }
}
