import 'package:flutter/material.dart';

/* Text Free
    Autogenerated by FlutLab FTF Generator
  */
class FreeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Free''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 40.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
