import 'package:flutter/material.dart';

/* Text Your credit to use is 2 hours
    Autogenerated by FlutLab FTF Generator
  */
class Yourcredittouseis2hoursWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Your credit to use is 2 hours''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
