import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/ClassWidget10.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/SessionLinkWidget2.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/TopicWidget7.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/BTC1Widget21.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Polygon5Widget6.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Httpsmrprofesorzoomus4578FG24DE58R63SF8Widget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/ClassDetailWidget7.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/ResourcesWidget4.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/EndTimeWidget6.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/CreateClassWidget3.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/FlutLab1700Widget4.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/CourseWidget10.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Polygon7Widget3.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Ellipse4Widget17.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle45Widget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/BTP1Widget21.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/StatusWidget6.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle9Widget22.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle44Widget2.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle29Widget8.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle18Widget16.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/SWidget3.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle10Widget22.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/PhysicalWidget7.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/ScheduleWidget4.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle8Widget23.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle46Widget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Polygon6Widget3.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle14Widget11.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/PabloGabrielWidget6.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/MendezJimenezWidget6.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle12Widget21.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle17Widget14.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/BTH1Widget21.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle47Widget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Physical_SmoothLineMotiondocWidget.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/FlutLab2Widget10.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/HoursWidget11.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/SmoothLineMotionWidget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/StartTimeWidget12.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/FlutLab1900Widget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle49Widget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle48Widget1.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Physical_SmoothLineMotionpptWidget.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle16Widget21.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/Rectangle13Widget21.dart';
import 'package:flutterapp/figma/teachercreateclassexamplewidget/widgets/StudentWidget4.dart';

/* Frame Teacher Create Class Example
    Autogenerated by FlutLab FTF Generator
  */
class TeacherCreateClassExampleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget22(),
          ),
          Positioned(
            left: 23.0,
            top: 514.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget21(),
          ),
          Positioned(
            left: 44.0,
            top: 533.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget7(),
          ),
          Positioned(
            left: 44.0,
            top: 568.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget7(),
          ),
          Positioned(
            left: 134.0,
            top: 568.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 15.0,
            child: SmoothLineMotionWidget1(),
          ),
          Positioned(
            left: 134.0,
            top: 598.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 15.0,
            child: PhysicalWidget7(),
          ),
          Positioned(
            left: 134.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 15.0,
            child: FlutLab1700Widget4(),
          ),
          Positioned(
            left: 134.0,
            top: 684.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 15.0,
            child: ScheduleWidget4(),
          ),
          Positioned(
            left: 134.0,
            top: 658.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 15.0,
            child: FlutLab1900Widget1(),
          ),
          Positioned(
            left: 44.0,
            top: 598.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget10(),
          ),
          Positioned(
            left: 44.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget12(),
          ),
          Positioned(
            left: 44.0,
            top: 658.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget6(),
          ),
          Positioned(
            left: 44.0,
            top: 688.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget6(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget22(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget10(),
          ),
          Positioned(
            left: 230.0,
            top: 727.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget21(),
          ),
          Positioned(
            left: 239.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 17.0,
            child: CreateClassWidget3(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget23(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget21(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget21(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget21(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget21(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget14(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget16(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget17(),
          ),
          Positioned(
            left: 137.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 101.0,
            height: 18.0,
            child: PabloGabrielWidget6(),
          ),
          Positioned(
            left: 116.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 34.0,
            child: MendezJimenezWidget6(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget10(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: SWidget3(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget11(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: StudentWidget4(),
          ),
          Positioned(
            left: 24.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 141.0,
            child: Rectangle45Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle14Widget11(),
          ),
          Positioned(
            left: 131.0,
            top: 256.0,
            right: null,
            bottom: null,
            width: 114.0,
            height: 25.0,
            child: SessionLinkWidget2(),
          ),
          Positioned(
            left: 23.0,
            top: 288.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 26.0,
            child: Rectangle44Widget2(),
          ),
          Positioned(
            left: 58.0,
            top: 293.0,
            right: null,
            bottom: null,
            width: 260.0,
            height: 13.0,
            child: Httpsmrprofesorzoomus4578FG24DE58R63SF8Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 331.0,
            height: 38.0,
            child: Rectangle29Widget8(),
          ),
          Positioned(
            left: 323.0,
            top: 352.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon5Widget6(),
          ),
          Positioned(
            left: 145.0,
            top: 348.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 30.0,
            child: ResourcesWidget4(),
          ),
          Positioned(
            left: 37.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 257.0,
            height: 27.0,
            child: Rectangle46Widget1(),
          ),
          Positioned(
            left: 53.0,
            top: 404.0,
            right: null,
            bottom: null,
            width: 172.0,
            height: 13.0,
            child: Physical_SmoothLineMotiondocWidget(),
          ),
          Positioned(
            left: 37.0,
            top: 440.0,
            right: null,
            bottom: null,
            width: 257.0,
            height: 27.0,
            child: Rectangle48Widget1(),
          ),
          Positioned(
            left: 53.0,
            top: 447.0,
            right: null,
            bottom: null,
            width: 168.0,
            height: 13.0,
            child: Physical_SmoothLineMotionpptWidget(),
          ),
          Positioned(
            left: 309.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 27.0,
            child: Rectangle47Widget1(),
          ),
          Positioned(
            left: 309.0,
            top: 440.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 27.0,
            child: Rectangle49Widget1(),
          ),
          Positioned(
            left: 288.0,
            top: 420.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon6Widget3(),
          ),
          Positioned(
            left: 288.0,
            top: 463.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon7Widget3(),
          )
        ]),
      ),
    ));
  }
}
