import 'package:flutter/material.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle9Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/JobApplicationTeacherWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/CompletetherequerimentsforyourjobapplicationWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/AddyourprofilelinkonlinkendWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/OtherWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/SelectthecoursesyouteachWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/SendWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/SigninWidget8.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle10Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/BT1Widget1.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/E01Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle25Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle26Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/InordertoverifyyourexperienceandprovideagoodservicetoallouruserstudentswewantyoutoshareyourLinkdinprofilewithusPleaseenteryouralinktoyourprofileWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/MathematicsWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/LLK1Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/ChemistryWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle8Widget1.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle20Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/H02Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/F01Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle21Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/YocanselectseveralWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle24Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle4Widget7.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle1Widget8.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/PhysicalWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle27Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/HistoryWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/BLogo1Widget7.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/M02Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Line12Widget1.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Rectangle2Widget7.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/RegisterWidget11.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/O02Widget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/EconomyWidget.dart';
import 'package:flutterapp/figma/experiencedatateacherwidget/widgets/Q02Widget.dart';

/* Frame Experience Data Teacher
    Autogenerated by FlutLab FTF Generator
  */
class ExperienceDataTeacherWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 323.0,
            child: BT1Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget8(),
          ),
          Positioned(
            left: 188.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget7(),
          ),
          Positioned(
            left: 73.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget8(),
          ),
          Positioned(
            left: 239.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget11(),
          ),
          Positioned(
            left: 0.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 653.0,
            child: Rectangle2Widget7(),
          ),
          Positioned(
            left: 35.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child: CompletetherequerimentsforyourjobapplicationWidget(),
          ),
          Positioned(
            left: 72.0,
            top: 221.0,
            right: null,
            bottom: null,
            width: 232.0,
            height: 23.0,
            child: JobApplicationTeacherWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle8Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 303.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 39.0,
            child: Rectangle10Widget(),
          ),
          Positioned(
            left: 164.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 21.0,
            child: SendWidget(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo1Widget7(),
          ),
          Positioned(
            left: 64.0,
            top: 356.0,
            right: null,
            bottom: null,
            width: 247.0,
            height: 39.0,
            child: Rectangle9Widget(),
          ),
          Positioned(
            left: 168.0,
            top: 303.0,
            right: null,
            bottom: null,
            width: 39.0,
            height: 39.0,
            child: LLK1Widget(),
          ),
          Positioned(
            left: 82.0,
            top: 367.0,
            right: null,
            bottom: null,
            width: 212.0,
            height: 17.0,
            child: AddyourprofilelinkonlinkendWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 60.0,
            child:
                InordertoverifyyourexperienceandprovideagoodservicetoallouruserstudentswewantyoutoshareyourLinkdinprofilewithusPleaseenteryouralinktoyourprofileWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 486.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line12Widget1(),
          ),
          Positioned(
            left: 38.0,
            top: 502.0,
            right: null,
            bottom: null,
            width: 129.0,
            height: 30.0,
            child: SelectthecoursesyouteachWidget(),
          ),
          Positioned(
            left: 217.0,
            top: 708.0,
            right: null,
            bottom: null,
            width: 123.0,
            height: 15.0,
            child: YocanselectseveralWidget(),
          ),
          Positioned(
            left: 116.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle20Widget(),
          ),
          Positioned(
            left: 136.0,
            top: 673.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 13.0,
            child: OtherWidget(),
          ),
          Positioned(
            left: 36.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle21Widget(),
          ),
          Positioned(
            left: 51.0,
            top: 673.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 13.0,
            child: EconomyWidget(),
          ),
          Positioned(
            left: 277.0,
            top: 546.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle24Widget(),
          ),
          Positioned(
            left: 292.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 13.0,
            child: PhysicalWidget(),
          ),
          Positioned(
            left: 131.0,
            top: 636.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: O02Widget(),
          ),
          Positioned(
            left: 197.0,
            top: 546.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle25Widget(),
          ),
          Positioned(
            left: 209.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 13.0,
            child: ChemistryWidget(),
          ),
          Positioned(
            left: 211.0,
            top: 554.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: Q02Widget(),
          ),
          Positioned(
            left: 117.0,
            top: 546.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle26Widget(),
          ),
          Positioned(
            left: 134.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 28.0,
            height: 13.0,
            child: HistoryWidget(),
          ),
          Positioned(
            left: 132.0,
            top: 554.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: H02Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 546.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle27Widget(),
          ),
          Positioned(
            left: 45.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 13.0,
            child: MathematicsWidget(),
          ),
          Positioned(
            left: 51.0,
            top: 554.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: M02Widget(),
          ),
          Positioned(
            left: 291.0,
            top: 554.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: F01Widget(),
          ),
          Positioned(
            left: 50.0,
            top: 636.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: E01Widget(),
          )
        ]),
      ),
    ));
  }
}
