import 'package:flutter/material.dart';

/* Rectangle Rectangle 9
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle9Widget23 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(13.0),
      child: Container(
        width: 375.0,
        height: 94.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(13.0),
          border: Border.all(
            width: 0.5,
            color: Color.fromARGB(255, 233, 233, 233),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(13.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
