import 'package:flutter/material.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Line4Widget1.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Line2Widget3.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Rectangle4Widget4.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Line5Widget1.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/MmaaWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/MC1Widget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/AddyourCardWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/BS1Widget2.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Rectangle1Widget5.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/WeneedyoutoaddyourpaymentmethodtofinishtheselectionprocessofyoursubscriptionWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/NameLastNameWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/EmailWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/GetStartedWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/CVVWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Line3Widget2.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Rectangle2Widget4.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Polygon2Widget1.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/CardNumberWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/SigninWidget4.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/RegisterWidget5.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Line6Widget1.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Rectangle3Widget4.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/MastercardWidget.dart';
import 'package:flutterapp/figma/addcreditcardwidget/widgets/Polygon1Widget.dart';

/* Frame Add Credit Card
    Autogenerated by FlutLab FTF Generator
  */
class AddCreditCardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 323.0,
            child: BS1Widget2(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget5(),
          ),
          Positioned(
            left: 188.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget4(),
          ),
          Positioned(
            left: 73.0,
            top: 272.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget4(),
          ),
          Positioned(
            left: 239.0,
            top: 272.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget5(),
          ),
          Positioned(
            left: 0.0,
            top: 299.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 541.0,
            child: Rectangle2Widget4(),
          ),
          Positioned(
            left: 38.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 16.0,
            child: MmaaWidget(),
          ),
          Positioned(
            left: 268.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 16.0,
            child: CVVWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 124.0,
            height: 16.0,
            child: NameLastNameWidget(),
          ),
          Positioned(
            left: 144.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 16.0,
            child: EmailWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 493.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 16.0,
            child: CardNumberWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 737.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle3Widget4(),
          ),
          Positioned(
            left: 137.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 96.0,
            height: 21.0,
            child: GetStartedWidget(),
          ),
          Positioned(
            left: -24.0,
            top: -43.0,
            right: null,
            bottom: null,
            width: 423.0,
            height: 370.5035705566406,
            child: MC1Widget(),
          ),
          Positioned(
            left: 35.0,
            top: 364.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child:
                WeneedyoutoaddyourpaymentmethodtofinishtheselectionprocessofyoursubscriptionWidget(),
          ),
          Positioned(
            left: 119.0,
            top: 328.0,
            right: null,
            bottom: null,
            width: 137.0,
            height: 23.0,
            child: AddyourCardWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 683.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 0.0,
            child: Line2Widget3(),
          ),
          Positioned(
            left: 144.0,
            top: 684.0,
            right: null,
            bottom: null,
            width: 194.0,
            height: 0.0,
            child: Line6Widget1(),
          ),
          Positioned(
            left: 38.0,
            top: 600.0,
            right: null,
            bottom: null,
            width: 194.0,
            height: 0.0,
            child: Line3Widget2(),
          ),
          Positioned(
            left: 268.0,
            top: 600.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 0.0,
            child: Line5Widget1(),
          ),
          Positioned(
            left: 38.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line4Widget1(),
          ),
          Positioned(
            left: 309.0,
            top: 425.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Polygon1Widget(),
          ),
          Positioned(
            left: 117.0,
            top: 423.0,
            right: null,
            bottom: null,
            width: 141.0,
            height: 31.0,
            child: MastercardWidget(),
          ),
          Positioned(
            left: 66.0,
            top: 455.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Polygon2Widget1(),
          )
        ]),
      ),
    ));
  }
}
