import 'package:flutter/material.dart';

/* Rectangle DL 2
    Autogenerated by FlutLab FTF Generator
  */
class DL2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-1.00, -0.00, 0.00, 0.00, 0.00, -1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 25.0,
          height: 25.0,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: ExactAssetImage(
                "assets/images/282738e94cb555f1e826369dc8bddca12526d17d.png",
              ),
              fit: BoxFit.cover,
            ),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Image.asset(
              "assets/images/282738e94cb555f1e826369dc8bddca12526d17d.png",
              color: null,
              fit: BoxFit.cover,
              width: 25.0,
              height: 25.0,
              colorBlendMode: BlendMode.dstATop,
            ),
          ),
        ));
  }
}
