import 'package:flutter/material.dart';

/* Rectangle FP 1
    Autogenerated by FlutLab FTF Generator
  */
class FP1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 35.0,
      height: 35.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/75cef124fce1f309081ba0d81d7c2755ad2b303f.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/75cef124fce1f309081ba0d81d7c2755ad2b303f.png",
          color: null,
          fit: BoxFit.cover,
          width: 35.0,
          height: 35.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
