import 'package:flutter/material.dart';

/* Rectangle Rectangle 13
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle13Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 105.0,
        height: 27.9255313873291,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
          border: Border.all(
            width: 2.5,
            color: Color.fromARGB(255, 18, 204, 253),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(20.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(0, 255, 255, 255),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
