import 'package:flutter/material.dart';

/* Rectangle Rectangle 32
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle32Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 330.0,
        height: 38.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(12.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 102, 250, 2),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
