import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/WriteacommentWidget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/StatusWidget1.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/TeacherWidget3.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/FlutLab900Widget2.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/FinishedWidget1.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle25Widget3.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/TWidget2.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/BTP1Widget9.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/BTH1Widget9.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle30Widget1.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/ClassWidget4.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle13Widget9.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle10Widget10.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/LiteratureWidget2.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/LiteraryGenresWidget1.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/HoursWidget5.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Ellipse4Widget6.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/EE1Widget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/EE5Widget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/TopicWidget2.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/EE3Widget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/FlutLab700Widget7.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle9Widget10.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/EndTimeWidget1.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/FlutLab2Widget3.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle12Widget9.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle29Widget3.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/EE4Widget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle18Widget9.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/EE2Widget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/StartTimeWidget5.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/SendWidget2.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/ClassHistoryWidget4.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/ClassDetailWidget2.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle16Widget9.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/TorresSalvatoreWidget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle8Widget11.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/CourseWidget4.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/BTC1Widget9.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/ArturoFelipeWidget.dart';
import 'package:flutterapp/figma/studentreviewwidget/widgets/Rectangle17Widget6.dart';

/* Frame Student Review
    Autogenerated by FlutLab FTF Generator
  */
class StudentReviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget10(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget10(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget4(),
          ),
          Positioned(
            left: 229.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget9(),
          ),
          Positioned(
            left: 241.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 17.0,
            child: ClassHistoryWidget4(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget11(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget9(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget9(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget9(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget9(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 198.0,
            child: Rectangle25Widget3(),
          ),
          Positioned(
            left: 43.0,
            top: 267.0,
            right: null,
            bottom: null,
            width: 290.0,
            height: 95.0,
            child: Rectangle29Widget3(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget6(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget9(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget6(),
          ),
          Positioned(
            left: 141.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 92.0,
            height: 18.0,
            child: ArturoFelipeWidget(),
          ),
          Positioned(
            left: 107.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 162.0,
            height: 34.0,
            child: TorresSalvatoreWidget(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget3(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: TWidget2(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget5(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: TeacherWidget3(),
          ),
          Positioned(
            left: 42.0,
            top: 405.0,
            right: null,
            bottom: null,
            width: 292.0,
            height: 26.0,
            child: Rectangle30Widget1(),
          ),
          Positioned(
            left: 174.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EE1Widget(),
          ),
          Positioned(
            left: 212.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EE2Widget(),
          ),
          Positioned(
            left: 136.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EE3Widget(),
          ),
          Positioned(
            left: 98.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EE4Widget(),
          ),
          Positioned(
            left: 250.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: EE5Widget(),
          ),
          Positioned(
            left: 56.0,
            top: 279.0,
            right: null,
            bottom: null,
            width: 102.0,
            height: 15.0,
            child: WriteacommentWidget(),
          ),
          Positioned(
            left: 168.0,
            top: 409.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 18.0,
            child: SendWidget2(),
          ),
          Positioned(
            left: 24.0,
            top: 477.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget9(),
          ),
          Positioned(
            left: 45.0,
            top: 496.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget2(),
          ),
          Positioned(
            left: 45.0,
            top: 531.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget2(),
          ),
          Positioned(
            left: 135.0,
            top: 531.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 15.0,
            child: LiteraryGenresWidget1(),
          ),
          Positioned(
            left: 135.0,
            top: 561.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 15.0,
            child: LiteratureWidget2(),
          ),
          Positioned(
            left: 135.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget7(),
          ),
          Positioned(
            left: 135.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 15.0,
            child: FinishedWidget1(),
          ),
          Positioned(
            left: 137.0,
            top: 621.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab900Widget2(),
          ),
          Positioned(
            left: 45.0,
            top: 561.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget4(),
          ),
          Positioned(
            left: 45.0,
            top: 591.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget5(),
          ),
          Positioned(
            left: 45.0,
            top: 621.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget1(),
          ),
          Positioned(
            left: 45.0,
            top: 651.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget1(),
          )
        ]),
      ),
    ));
  }
}
