import 'package:flutter/material.dart';

/* Text A class requires a minimum 2 hours
    Autogenerated by FlutLab FTF Generator
  */
class Aclassrequiresaminimum2hoursWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''A class requires a minimum 2 hours''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 1, 1, 1),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
