import 'package:flutter/material.dart';

/* Rectangle M1 1
    Autogenerated by FlutLab FTF Generator
  */
class M11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 34.0,
      height: 34.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/8c481f885f2a78b21f43cfe9eb21d9c0200679fc.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/8c481f885f2a78b21f43cfe9eb21d9c0200679fc.png",
          color: null,
          fit: BoxFit.cover,
          width: 34.0,
          height: 34.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
