import 'package:flutter/material.dart';

/* Rectangle N1 1
    Autogenerated by FlutLab FTF Generator
  */
class N11Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 28.823530197143555,
      height: 35.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/b72bce5d8fe9bcaae6d358d5146338f8e6c3e98f.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/b72bce5d8fe9bcaae6d358d5146338f8e6c3e98f.png",
          color: null,
          fit: BoxFit.cover,
          width: 28.823530197143555,
          height: 35.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
