import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* RegularPolygon Polygon 5
    Autogenerated by FlutLab FTF Generator
  */
class Polygon5Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-1.00, -0.00, 0.00, 0.00, 0.00, -1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 20.0,
          height: 20.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M8.26795 3C9.03775 1.66667 10.9623 1.66667 11.7321 3L16.9282 12C17.698 13.3333 16.7358 15 15.1962 15L4.80385 15C3.26425 15 2.302 13.3333 3.0718 12L8.26795 3Z')
              ..color = Color.fromARGB(255, 255, 255, 255),
          ]),
        ));
  }
}
