import 'package:flutter/material.dart';

/* Text Start Class
    Autogenerated by FlutLab FTF Generator
  */
class StartClassWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Start Class''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 15.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
