import 'package:flutter/material.dart';

/* Rectangle BT 2
    Autogenerated by FlutLab FTF Generator
  */
class BT2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 323.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/81f06e24e16a342838cb04f281fd6e2e06e90439.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/81f06e24e16a342838cb04f281fd6e2e06e90439.png",
          color: null,
          fit: BoxFit.cover,
          width: 375.0,
          height: 323.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
