import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* RegularPolygon Polygon 4
    Autogenerated by FlutLab FTF Generator
  */
class Polygon4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-1.00, -0.00, 0.00, 0.00, 0.00, -1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 24.0,
          height: 24.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M9.40192 4.5C10.5566 2.5 13.4434 2.5 14.5981 4.5L19.7942 13.5C20.9489 15.5 19.5056 18 17.1962 18L6.80385 18C4.49445 18 3.05107 15.5 4.20577 13.5L9.40192 4.5Z')
              ..color = Color.fromARGB(255, 18, 204, 253),
          ]),
        ));
  }
}
