import 'package:flutter/material.dart';

/* Text Teacher Registration
    Autogenerated by FlutLab FTF Generator
  */
class TeacherRegistrationWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Teacher Registration''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 19.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 14, 36, 220),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
