import 'package:flutter/material.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/EnteraPasswordWidget1.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Rectangle3Widget5.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/EnteryourEmailWidget1.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Rectangle1Widget6.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Rectangle4Widget5.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Line3Widget3.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Polygon1Widget1.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/BLogo1Widget5.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/EnteranUsernameWidget1.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Rectangle5Widget1.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/SigninWidget5.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Line2Widget4.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/PM1Widget.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/TeacherWidget.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Line1Widget3.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Polygon2Widget2.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/PW1Widget.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/BPrincipal1Widget3.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/ChooseaCategoryWidget1.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/RegisterWidget6.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/Rectangle2Widget5.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/NextWidget1.dart';
import 'package:flutterapp/figma/registerteacherwidget/widgets/EnterthedataintheestablishedfieldsandselectacategoryWidget1.dart';

/* Frame Register Teacher
    Autogenerated by FlutLab FTF Generator
  */
class RegisterTeacherWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: BPrincipal1Widget3(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget6(),
          ),
          Positioned(
            left: 188.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget5(),
          ),
          Positioned(
            left: 73.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget5(),
          ),
          Positioned(
            left: 239.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget6(),
          ),
          Positioned(
            left: 0.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 653.0,
            child: Rectangle2Widget5(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo1Widget5(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle3Widget5(),
          ),
          Positioned(
            left: 166.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 21.0,
            child: NextWidget1(),
          ),
          Positioned(
            left: 38.0,
            top: 683.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line2Widget4(),
          ),
          Positioned(
            left: 38.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 16.0,
            child: EnteraPasswordWidget1(),
          ),
          Positioned(
            left: 38.0,
            top: 600.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line1Widget3(),
          ),
          Positioned(
            left: 38.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 16.0,
            child: EnteryourEmailWidget1(),
          ),
          Positioned(
            left: 38.0,
            top: 514.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line3Widget3(),
          ),
          Positioned(
            left: 38.0,
            top: 490.0,
            right: null,
            bottom: null,
            width: 120.0,
            height: 16.0,
            child: EnteranUsernameWidget1(),
          ),
          Positioned(
            left: 125.0,
            top: 315.0,
            right: null,
            bottom: null,
            width: 125.0,
            height: 125.0,
            child: Rectangle5Widget1(),
          ),
          Positioned(
            left: 116.0,
            top: 313.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 128.0,
            child: PM1Widget(),
          ),
          Positioned(
            left: 178.0,
            top: 313.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 128.0,
            child: PW1Widget(),
          ),
          Positioned(
            left: 313.0,
            top: 362.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Polygon1Widget1(),
          ),
          Positioned(
            left: 70.0,
            top: 392.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Polygon2Widget2(),
          ),
          Positioned(
            left: 35.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child:
                EnterthedataintheestablishedfieldsandselectacategoryWidget1(),
          ),
          Positioned(
            left: 97.0,
            top: 221.0,
            right: null,
            bottom: null,
            width: 182.0,
            height: 23.0,
            child: ChooseaCategoryWidget1(),
          ),
          Positioned(
            left: 154.0,
            top: 451.0,
            right: null,
            bottom: null,
            width: 67.0,
            height: 21.0,
            child: TeacherWidget(),
          )
        ]),
      ),
    ));
  }
}
