import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined0472/widgets/SignInWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/PasswordWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/Rectangle4Widget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/Line2Widget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/RegisterWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/WelcometoWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/BPrincipal1Widget1.dart';
import 'package:flutterapp/figma/undefined0472/widgets/DonthaveanaccountCreateyouraccountittakelessthanaminuteWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/Line1Widget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/TUTOFASTWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/Rectangle3Widget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/Rectangle1Widget1.dart';
import 'package:flutterapp/figma/undefined0472/widgets/ForgetPasswordWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/EmailUsernameWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/Rectangle2Widget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/SigninWidget.dart';
import 'package:flutterapp/figma/undefined0472/widgets/BLogo1Widget1.dart';

/* Frame Log In
    Autogenerated by FlutLab FTF Generator
  */
class Undefined0472 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: BPrincipal1Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget1(),
          ),
          Positioned(
            left: 28.0,
            top: 389.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 424.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 420.0,
            child: Rectangle2Widget(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo1Widget1(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle3Widget(),
          ),
          Positioned(
            left: 159.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 53.0,
            height: 21.0,
            child: SignInWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 465.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child:
                DonthaveanaccountCreateyouraccountittakelessthanaminuteWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 569.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line1Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 545.0,
            right: null,
            bottom: null,
            width: 103.0,
            height: 16.0,
            child: EmailUsernameWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 652.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line2Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 59.0,
            height: 16.0,
            child: PasswordWidget(),
          ),
          Positioned(
            left: 227.0,
            top: 666.0,
            right: null,
            bottom: null,
            width: 111.0,
            height: 16.0,
            child: ForgetPasswordWidget(),
          ),
          Positioned(
            left: 39.0,
            top: 197.0,
            right: null,
            bottom: null,
            width: 298.0,
            height: 120.0,
            child: TUTOFASTWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 182.0,
            right: null,
            bottom: null,
            width: 131.0,
            height: 30.0,
            child: WelcometoWidget(),
          ),
          Positioned(
            left: 84.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget(),
          ),
          Positioned(
            left: 244.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget(),
          )
        ]),
      ),
    ));
  }
}
