import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle10Widget5.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/BookaclasswithateacherwhonevershowsupThatiswhyIwantthehoursofthereservedclasstobereturnedtomeortobeassignedanotherteacherurgentlyWidget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/SettingsWidget1.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle31Widget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/TheteachernevershowedupWidget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle25Widget2.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle22Widget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle8Widget6.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle12Widget4.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle9Widget5.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/ReportyourproblemasWidget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/ComplaintCenterWidget1.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Polygon6Widget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle18Widget4.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/SubscriptionWidget1.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle29Widget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/BTH1Widget4.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle11Widget4.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Wetakecareofyourproblems247Widget1.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/ProfileWidget1.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/SessionProblemsWidget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/NicolasAlexanderWidget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle16Widget4.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/SD11Widget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/QuirozRisopatronWidget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/BTP1Widget4.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle30Widget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Line2Widget6.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/SendWidget1.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Polygon7Widget.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Ellipse4Widget1.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/BTC1Widget4.dart';
import 'package:flutterapp/figma/studentcomplaintcenterwidget/widgets/Rectangle13Widget4.dart';

/* Frame Student Complaint Center
    Autogenerated by FlutLab FTF Generator
  */
class StudentComplaintCenterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget5(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget5(),
          ),
          Positioned(
            left: 45.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 41.0,
            height: 17.0,
            child: ProfileWidget1(),
          ),
          Positioned(
            left: 13.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget4(),
          ),
          Positioned(
            left: 284.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 17.0,
            child: SettingsWidget1(),
          ),
          Positioned(
            left: 147.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 17.0,
            child: SubscriptionWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget6(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget4(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget4(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget4(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget4(),
          ),
          Positioned(
            left: 23.0,
            top: -88.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 198.0,
            child: Rectangle16Widget4(),
          ),
          Positioned(
            left: 92.0,
            top: 79.0,
            right: null,
            bottom: null,
            width: 191.0,
            height: 13.0,
            child: Wetakecareofyourproblems247Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 140.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 80.0,
            child: Rectangle11Widget4(),
          ),
          Positioned(
            left: 338.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: Polygon7Widget(),
          ),
          Positioned(
            left: 23.0,
            top: 250.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 61.0,
            child: Rectangle22Widget(),
          ),
          Positioned(
            left: 41.0,
            top: 291.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 0.0,
            child: Line2Widget6(),
          ),
          Positioned(
            left: 23.0,
            top: 341.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 168.0,
            child: Rectangle25Widget2(),
          ),
          Positioned(
            left: 23.0,
            top: 539.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 95.0,
            child: Rectangle31Widget(),
          ),
          Positioned(
            left: 23.0,
            top: 539.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 95.0,
            child: Rectangle18Widget4(),
          ),
          Positioned(
            left: 170.0,
            top: 566.0,
            right: null,
            bottom: null,
            width: 132.0,
            height: 18.0,
            child: NicolasAlexanderWidget(),
          ),
          Positioned(
            left: 153.0,
            top: 581.0,
            right: null,
            bottom: null,
            width: 168.0,
            height: 34.0,
            child: QuirozRisopatronWidget(),
          ),
          Positioned(
            left: 41.0,
            top: 470.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 26.0,
            child: Rectangle30Widget(),
          ),
          Positioned(
            left: 41.0,
            top: 357.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 101.0,
            child: Rectangle29Widget(),
          ),
          Positioned(
            left: 86.0,
            top: 41.0,
            right: null,
            bottom: null,
            width: 207.0,
            height: 42.0,
            child: ComplaintCenterWidget1(),
          ),
          Positioned(
            left: 338.0,
            top: 286.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon6Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 270.0,
            right: null,
            bottom: null,
            width: 190.0,
            height: 16.0,
            child: TheteachernevershowedupWidget(),
          ),
          Positioned(
            left: 168.0,
            top: 474.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 18.0,
            child: SendWidget1(),
          ),
          Positioned(
            left: 55.0,
            top: 371.0,
            right: null,
            bottom: null,
            width: 268.0,
            height: 60.0,
            child:
                BookaclasswithateacherwhonevershowsupThatiswhyIwantthehoursofthereservedclasstobereturnedtomeortobeassignedanotherteacherurgentlyWidget(),
          ),
          Positioned(
            left: 45.0,
            top: 553.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 70.0,
            child: Ellipse4Widget1(),
          ),
          Positioned(
            left: 133.0,
            top: 186.0,
            right: null,
            bottom: null,
            width: 174.0,
            height: 13.0,
            child: ReportyourproblemasWidget(),
          ),
          Positioned(
            left: 133.0,
            top: 158.0,
            right: null,
            bottom: null,
            width: 147.0,
            height: 30.0,
            child: SessionProblemsWidget(),
          ),
          Positioned(
            left: 69.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 50.0,
            child: SD11Widget(),
          )
        ]),
      ),
    ));
  }
}
