import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/BTH1Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/ChoosetheCourseWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/FlutLab250Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/CreditWidget3.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/O01Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/OtherWidget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle14Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/NotificationsWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle13Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/StartTimeWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle17Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle16Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/MathematicsWidget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle19Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/BTC1Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/FlutLab700Widget.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/HWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle20Widget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/M11Widget.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/AssignedDateWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/ChemistryWidget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/BTP1Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/N11Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Aclassrequiresaminimum2hoursWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/ReserveWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle9Widget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/SumofquadraticvariablesWidget.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle10Widget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle21Widget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle15Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/FastClassWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle12Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Q01Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/MondayWidget.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle18Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle11Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Ellipse1Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/TutoFastWidget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Rectangle8Widget3.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/TopictoStudyWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/H01Widget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/HistoryWidget2.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/FindyourtutorWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/IdealSafeandReliableWidget1.dart';
import 'package:flutterapp/figma/studentsearchwidget/widgets/Line7Widget2.dart';

/* Frame Student Search
    Autogenerated by FlutLab FTF Generator
  */
class StudentSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget2(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget2(),
          ),
          Positioned(
            left: 60.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 17.0,
            child: FastClassWidget1(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget1(),
          ),
          Positioned(
            left: 240.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 17.0,
            child: NotificationsWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget3(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget1(),
          ),
          Positioned(
            left: 168.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 567.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 115.0,
            child: Rectangle11Widget1(),
          ),
          Positioned(
            left: 277.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle18Widget1(),
          ),
          Positioned(
            left: 297.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 13.0,
            child: OtherWidget2(),
          ),
          Positioned(
            left: 291.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: O01Widget1(),
          ),
          Positioned(
            left: 197.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle19Widget1(),
          ),
          Positioned(
            left: 209.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 13.0,
            child: ChemistryWidget2(),
          ),
          Positioned(
            left: 211.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: Q01Widget1(),
          ),
          Positioned(
            left: 117.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle20Widget2(),
          ),
          Positioned(
            left: 134.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 28.0,
            height: 13.0,
            child: HistoryWidget2(),
          ),
          Positioned(
            left: 132.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: H01Widget1(),
          ),
          Positioned(
            left: 37.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle21Widget2(),
          ),
          Positioned(
            left: 45.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 13.0,
            child: MathematicsWidget2(),
          ),
          Positioned(
            left: 37.0,
            top: 577.0,
            right: null,
            bottom: null,
            width: 110.0,
            height: 16.0,
            child: ChoosetheCourseWidget1(),
          ),
          Positioned(
            left: 23.0,
            top: 141.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 93.0,
            child: Rectangle14Widget1(),
          ),
          Positioned(
            left: 42.0,
            top: 186.0,
            right: null,
            bottom: null,
            width: 262.0,
            height: 40.0,
            child: IdealSafeandReliableWidget1(),
          ),
          Positioned(
            left: 42.0,
            top: 170.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 19.0,
            child: FindyourtutorWidget1(),
          ),
          Positioned(
            left: 23.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 61.0,
            child: TutoFastWidget2(),
          ),
          Positioned(
            left: 318.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse1Widget1(),
          ),
          Positioned(
            left: 276.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 28.823530197143555,
            height: 35.0,
            child: N11Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 358.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 179.0,
            child: Rectangle16Widget1(),
          ),
          Positioned(
            left: 110.0,
            top: 501.0,
            right: null,
            bottom: null,
            width: 157.0,
            height: 15.0,
            child: SumofquadraticvariablesWidget(),
          ),
          Positioned(
            left: 140.0,
            top: 476.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 17.0,
            child: TopictoStudyWidget1(),
          ),
          Positioned(
            left: 218.0,
            top: 418.0,
            right: null,
            bottom: null,
            width: 99.0,
            height: 17.0,
            child: AssignedDateWidget1(),
          ),
          Positioned(
            left: 243.0,
            top: 443.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 15.0,
            child: MondayWidget(),
          ),
          Positioned(
            left: 96.0,
            top: 445.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget(),
          ),
          Positioned(
            left: 76.0,
            top: 418.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 17.0,
            child: StartTimeWidget1(),
          ),
          Positioned(
            left: 187.0,
            top: 421.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 0.0,
            child: Line7Widget2(),
          ),
          Positioned(
            left: 37.0,
            top: 371.0,
            right: null,
            bottom: null,
            width: 302.0,
            height: 30.0,
            child: Rectangle17Widget1(),
          ),
          Positioned(
            left: 158.0,
            top: 377.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: ReserveWidget1(),
          ),
          Positioned(
            left: 23.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle15Widget1(),
          ),
          Positioned(
            left: 55.0,
            top: 274.0,
            right: null,
            bottom: null,
            width: 49.0,
            height: 48.0,
            child: FlutLab250Widget1(),
          ),
          Positioned(
            left: 107.0,
            top: 280.0,
            right: null,
            bottom: null,
            width: 19.0,
            height: 37.0,
            child: HWidget1(),
          ),
          Positioned(
            left: 144.0,
            top: 277.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 21.0,
            child: CreditWidget3(),
          ),
          Positioned(
            left: 144.0,
            top: 299.0,
            right: null,
            bottom: null,
            width: 184.0,
            height: 13.0,
            child: Aclassrequiresaminimum2hoursWidget1(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget1(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget1(),
          ),
          Positioned(
            left: 51.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: M11Widget(),
          )
        ]),
      ),
    ));
  }
}
