import 'package:flutter/material.dart';

/* Rectangle EQ 2
    Autogenerated by FlutLab FTF Generator
  */
class EQ2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 30.0,
      height: 30.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/0febee0cc0a0c188ad0ba24177c1f91f15bafbdb.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/0febee0cc0a0c188ad0ba24177c1f91f15bafbdb.png",
          color: null,
          fit: BoxFit.cover,
          width: 30.0,
          height: 30.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
