import 'package:flutter/material.dart';

/* Rectangle Rectangle 30
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle30Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(12.0),
      child: Container(
        width: 292.0,
        height: 26.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            width: 2.0,
            color: Color.fromARGB(255, 102, 250, 2),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(12.0),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 102, 250, 2),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
