import 'package:flutter/material.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Rectangle3Widget3.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Rectangle4Widget3.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/SubcriptionWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Youaregiven2hoursascreditsfortheuseofrequestingavalidtutorwithin7daysWidget1.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Pay\$3000permothWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/SchoolWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/CreditWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/BLogo1Widget4.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/SigninWidget3.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/FreeWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Tryoutthefreetrialof7daysWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/AfteraddyourCreditCardWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/RegisterWidget4.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Rectangle7Widget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Rectangle2Widget3.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/BannersandvideoadvertisingwillberemovedWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/NoAdsWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/AddCardWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Rectangle1Widget4.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/NoAdsWidget1.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Youaregiven2hoursascreditsfortheuseofrequestingavalidtutorwithin7daysWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/FlutLab7daystrialWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/FlutLab30daysWidget.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/CreditWidget1.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/BS1Widget1.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget1.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/BannersandvideoadvertisingwillberemovedWidget1.dart';
import 'package:flutterapp/figma/subcriptionwidget1/widgets/Rectangle6Widget.dart';

/* Frame Subcription
    Autogenerated by FlutLab FTF Generator
  */
class SubcriptionWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 323.0,
            child: BS1Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget4(),
          ),
          Positioned(
            left: 188.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget3(),
          ),
          Positioned(
            left: 73.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget3(),
          ),
          Positioned(
            left: 239.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget4(),
          ),
          Positioned(
            left: 0.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 653.0,
            child: Rectangle2Widget3(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo1Widget4(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle3Widget3(),
          ),
          Positioned(
            left: 144.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 83.0,
            height: 21.0,
            child: AddCardWidget(),
          ),
          Positioned(
            left: 98.0,
            top: 702.0,
            right: null,
            bottom: null,
            width: 180.0,
            height: 16.0,
            child: Tryoutthefreetrialof7daysWidget(),
          ),
          Positioned(
            left: 272.0,
            top: 316.0,
            right: null,
            bottom: null,
            width: 206.0,
            height: 360.0,
            child: Rectangle7Widget(),
          ),
          Positioned(
            left: 289.0,
            top: 646.0,
            right: null,
            bottom: null,
            width: 109.0,
            height: 13.0,
            child: Pay$3000permothWidget(),
          ),
          Positioned(
            left: 289.0,
            top: 621.0,
            right: null,
            bottom: null,
            width: 57.0,
            height: 18.0,
            child: FlutLab30daysWidget(),
          ),
          Positioned(
            left: 289.0,
            top: 578.0,
            right: null,
            bottom: null,
            width: 132.0,
            height: 49.0,
            child: SchoolWidget(),
          ),
          Positioned(
            left: 309.0,
            top: 429.0,
            right: null,
            bottom: null,
            width: 153.0,
            height: 26.0,
            child: BannersandvideoadvertisingwillberemovedWidget(),
          ),
          Positioned(
            left: 309.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 53.0,
            height: 18.0,
            child: NoAdsWidget(),
          ),
          Positioned(
            left: 309.0,
            top: 360.0,
            right: null,
            bottom: null,
            width: 153.0,
            height: 36.0,
            child:
                Youaregiven2hoursascreditsfortheuseofrequestingavalidtutorwithin7daysWidget(),
          ),
          Positioned(
            left: 309.0,
            top: 337.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 18.0,
            child: CreditWidget(),
          ),
          Positioned(
            left: 34.0,
            top: 316.0,
            right: null,
            bottom: null,
            width: 206.0,
            height: 360.0,
            child: Rectangle6Widget(),
          ),
          Positioned(
            left: 52.0,
            top: 646.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 13.0,
            child: AfteraddyourCreditCardWidget(),
          ),
          Positioned(
            left: 52.0,
            top: 621.0,
            right: null,
            bottom: null,
            width: 79.0,
            height: 18.0,
            child: FlutLab7daystrialWidget(),
          ),
          Positioned(
            left: 50.0,
            top: 578.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 49.0,
            child: FreeWidget(),
          ),
          Positioned(
            left: 67.0,
            top: 429.0,
            right: null,
            bottom: null,
            width: 153.0,
            height: 26.0,
            child: BannersandvideoadvertisingwillberemovedWidget1(),
          ),
          Positioned(
            left: 67.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 53.0,
            height: 18.0,
            child: NoAdsWidget1(),
          ),
          Positioned(
            left: 68.0,
            top: 360.0,
            right: null,
            bottom: null,
            width: 153.0,
            height: 36.0,
            child:
                Youaregiven2hoursascreditsfortheuseofrequestingavalidtutorwithin7daysWidget1(),
          ),
          Positioned(
            left: 68.0,
            top: 337.0,
            right: null,
            bottom: null,
            width: 45.0,
            height: 18.0,
            child: CreditWidget1(),
          ),
          Positioned(
            left: 35.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child:
                EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget1(),
          ),
          Positioned(
            left: 136.0,
            top: 221.0,
            right: null,
            bottom: null,
            width: 104.0,
            height: 23.0,
            child: SubcriptionWidget(),
          )
        ]),
      ),
    ));
  }
}
