import 'package:flutter/material.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Rectangle2Widget1.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Rectangle5Widget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Polygon2Widget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Rectangle4Widget1.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/EnteraPasswordWidget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Rectangle3Widget1.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/StudentWidget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Line1Widget1.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/EnteryourEmailWidget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/SigninWidget1.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Line2Widget1.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/EW1Widget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/BLogo1Widget2.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/ChooseaCategoryWidget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/EnterthedataintheestablishedfieldsandselectacategoryWidget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/EM1Widget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/NextWidget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/BPrincipal1Widget2.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/EnteranUsernameWidget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Rectangle1Widget2.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Line3Widget.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/RegisterWidget1.dart';
import 'package:flutterapp/figma/registerstudentwidget/widgets/Polygon3Widget.dart';

/* Frame Register Student
    Autogenerated by FlutLab FTF Generator
  */
class RegisterStudentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: BPrincipal1Widget2(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget2(),
          ),
          Positioned(
            left: 188.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget1(),
          ),
          Positioned(
            left: 73.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget1(),
          ),
          Positioned(
            left: 239.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 653.0,
            child: Rectangle2Widget1(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo1Widget2(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle3Widget1(),
          ),
          Positioned(
            left: 166.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 21.0,
            child: NextWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 683.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line2Widget1(),
          ),
          Positioned(
            left: 38.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 16.0,
            child: EnteraPasswordWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 600.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line1Widget1(),
          ),
          Positioned(
            left: 38.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 16.0,
            child: EnteryourEmailWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 514.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line3Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 490.0,
            right: null,
            bottom: null,
            width: 120.0,
            height: 16.0,
            child: EnteranUsernameWidget(),
          ),
          Positioned(
            left: 125.0,
            top: 315.0,
            right: null,
            bottom: null,
            width: 125.0,
            height: 125.0,
            child: Rectangle5Widget(),
          ),
          Positioned(
            left: 116.0,
            top: 313.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 128.0,
            child: EM1Widget(),
          ),
          Positioned(
            left: 70.0,
            top: 392.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Polygon2Widget(),
          ),
          Positioned(
            left: 35.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child: EnterthedataintheestablishedfieldsandselectacategoryWidget(),
          ),
          Positioned(
            left: 97.0,
            top: 221.0,
            right: null,
            bottom: null,
            width: 182.0,
            height: 23.0,
            child: ChooseaCategoryWidget(),
          ),
          Positioned(
            left: 156.0,
            top: 451.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 21.0,
            child: StudentWidget(),
          ),
          Positioned(
            left: 178.0,
            top: 313.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 128.0,
            child: EW1Widget(),
          ),
          Positioned(
            left: 313.0,
            top: 362.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Polygon3Widget(),
          )
        ]),
      ),
    ));
  }
}
