import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/MarioSebastianWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle13Widget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle17Widget4.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/ClassDetailWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/EndTimeWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle16Widget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle10Widget7.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/BTH1Widget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/EnteryourSessionhereWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/TopicWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/FlutLab700Widget3.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/ClassHistoryWidget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/InProcessWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Polygon5Widget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/ThisbuttonredirectsyoutothesessionofyourclassWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle14Widget4.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle9Widget7.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Ellipse4Widget3.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle8Widget8.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/HoursWidget2.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/BTP1Widget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/ResourcesWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/CourseWidget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle29Widget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/TeacherWidget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle18Widget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle12Widget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/BTC1Widget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/CancelSessionWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/FlutLab900Widget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/ClassWidget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/FlutLab2Widget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/HistoryWidget6.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/TWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/StartTimeWidget3.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/SecondWorldWarWidget1.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/RiveraSotomayorWidget.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/Rectangle19Widget4.dart';
import 'package:flutterapp/figma/studentclassdetailwidget/widgets/StatusWidget.dart';

/* Frame Student Class Detail
    Autogenerated by FlutLab FTF Generator
  */
class StudentClassDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget7(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget7(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget1(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget6(),
          ),
          Positioned(
            left: 241.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 17.0,
            child: ClassHistoryWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget8(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget6(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget6(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget6(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget6(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle14Widget4(),
          ),
          Positioned(
            left: 76.0,
            top: 260.0,
            right: null,
            bottom: null,
            width: 222.0,
            height: 25.0,
            child: EnteryourSessionhereWidget(),
          ),
          Positioned(
            left: 53.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 271.0,
            height: 13.0,
            child: ThisbuttonredirectsyoutothesessionofyourclassWidget(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget4(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget6(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget3(),
          ),
          Positioned(
            left: 129.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 117.0,
            height: 18.0,
            child: MarioSebastianWidget(),
          ),
          Positioned(
            left: 105.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 166.0,
            height: 34.0,
            child: RiveraSotomayorWidget(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget1(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: TWidget(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget2(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: TeacherWidget1(),
          ),
          Positioned(
            left: 24.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 38.0,
            child: Rectangle29Widget1(),
          ),
          Positioned(
            left: 343.0,
            top: 372.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon5Widget1(),
          ),
          Positioned(
            left: 24.0,
            top: 654.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 31.0,
            child: Rectangle19Widget4(),
          ),
          Positioned(
            left: 129.0,
            top: 661.0,
            right: null,
            bottom: null,
            width: 110.0,
            height: 18.0,
            child: CancelSessionWidget(),
          ),
          Positioned(
            left: 24.0,
            top: 411.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget6(),
          ),
          Positioned(
            left: 45.0,
            top: 430.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget(),
          ),
          Positioned(
            left: 45.0,
            top: 465.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget(),
          ),
          Positioned(
            left: 135.0,
            top: 465.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 15.0,
            child: SecondWorldWarWidget1(),
          ),
          Positioned(
            left: 135.0,
            top: 495.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 15.0,
            child: HistoryWidget6(),
          ),
          Positioned(
            left: 135.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget3(),
          ),
          Positioned(
            left: 135.0,
            top: 581.0,
            right: null,
            bottom: null,
            width: 57.0,
            height: 15.0,
            child: InProcessWidget(),
          ),
          Positioned(
            left: 137.0,
            top: 555.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab900Widget1(),
          ),
          Positioned(
            left: 45.0,
            top: 495.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget1(),
          ),
          Positioned(
            left: 45.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget3(),
          ),
          Positioned(
            left: 45.0,
            top: 555.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget(),
          ),
          Positioned(
            left: 45.0,
            top: 585.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget(),
          ),
          Positioned(
            left: 143.0,
            top: 349.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 30.0,
            child: ResourcesWidget(),
          )
        ]),
      ),
    ));
  }
}
