import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/TWidget4.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle12Widget11.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/LiteratureWidget4.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Ellipse4Widget8.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/ClassWidget6.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle13Widget11.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle17Widget8.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/StartTimeWidget7.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/FlutLab900Widget4.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle16Widget11.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/ClassHistoryWidget6.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/HoursWidget7.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle8Widget13.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle10Widget12.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/FinishedWidget3.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/StatusWidget3.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/ArturoFelipeWidget2.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/LiteraryGenresWidget3.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/FlutLab700Widget9.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/BTH1Widget11.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/FlutLab2Widget5.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/BTC1Widget11.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle18Widget11.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/TeacherWidget5.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/ClassDetailWidget4.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/Rectangle9Widget12.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/BTP1Widget11.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/TorresSalvatoreWidget2.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/EndTimeWidget3.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/CourseWidget6.dart';
import 'package:flutterapp/figma/studentreviewfinishedwidget/widgets/TopicWidget4.dart';

/* Frame Student Review Finished
    Autogenerated by FlutLab FTF Generator
  */
class StudentReviewFinishedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget12(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget12(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget6(),
          ),
          Positioned(
            left: 229.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget11(),
          ),
          Positioned(
            left: 241.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 17.0,
            child: ClassHistoryWidget6(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget13(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget11(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget11(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget11(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget11(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget8(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget11(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget8(),
          ),
          Positioned(
            left: 141.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 92.0,
            height: 18.0,
            child: ArturoFelipeWidget2(),
          ),
          Positioned(
            left: 107.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 162.0,
            height: 34.0,
            child: TorresSalvatoreWidget2(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget5(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: TWidget4(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget7(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: TeacherWidget5(),
          ),
          Positioned(
            left: 24.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget11(),
          ),
          Positioned(
            left: 45.0,
            top: 268.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget4(),
          ),
          Positioned(
            left: 45.0,
            top: 303.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget4(),
          ),
          Positioned(
            left: 135.0,
            top: 303.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 15.0,
            child: LiteraryGenresWidget3(),
          ),
          Positioned(
            left: 135.0,
            top: 333.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 15.0,
            child: LiteratureWidget4(),
          ),
          Positioned(
            left: 135.0,
            top: 363.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget9(),
          ),
          Positioned(
            left: 135.0,
            top: 419.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 15.0,
            child: FinishedWidget3(),
          ),
          Positioned(
            left: 137.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab900Widget4(),
          ),
          Positioned(
            left: 45.0,
            top: 333.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget6(),
          ),
          Positioned(
            left: 45.0,
            top: 363.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget7(),
          ),
          Positioned(
            left: 45.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget3(),
          ),
          Positioned(
            left: 45.0,
            top: 423.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget3(),
          )
        ]),
      ),
    ));
  }
}
