import 'package:flutter/material.dart';

/* Text Add the Date
    Autogenerated by FlutLab FTF Generator
  */
class AddtheDateWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Add the Date''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 140, 140, 140),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
