import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/BTP1Widget20.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/SessionLinkWidget1.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle16Widget20.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle9Widget21.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle46Widget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/SWidget2.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/ClassWidget9.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle18Widget15.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Polygon6Widget2.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/ScheduleWidget3.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle48Widget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle14Widget10.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle44Widget1.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/StartTimeWidget11.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle13Widget20.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Polygon7Widget2.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Polygon5Widget5.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle10Widget21.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle45Widget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/StatusWidget5.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle49Widget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle17Widget13.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle47Widget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/PabloGabrielWidget5.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle8Widget22.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/PhysicalWidget6.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/StudentWidget3.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle12Widget20.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/BTH1Widget20.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/EnterthelinkofthevirtualsesionhereWidget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/HoursWidget10.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/FlutLab1900Widget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/MendezJimenezWidget5.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/CourseWidget9.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/FlutLab1700Widget3.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/EndTimeWidget5.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Ellipse4Widget16.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/SelectaPowertPointdocumentWidget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/BTC1Widget20.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/TopicWidget6.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/Rectangle29Widget7.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/SelectaWorddocumentWidget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/CreateClassWidget2.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/ResourcesWidget3.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/ClassDetailWidget6.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/SmoothLineMotionWidget.dart';
import 'package:flutterapp/figma/teachercreateclasswidget/widgets/FlutLab2Widget9.dart';

/* Frame Teacher Create Class
    Autogenerated by FlutLab FTF Generator
  */
class TeacherCreateClassWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget21(),
          ),
          Positioned(
            left: 23.0,
            top: 514.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget20(),
          ),
          Positioned(
            left: 44.0,
            top: 533.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget6(),
          ),
          Positioned(
            left: 44.0,
            top: 568.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget6(),
          ),
          Positioned(
            left: 134.0,
            top: 568.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 15.0,
            child: SmoothLineMotionWidget(),
          ),
          Positioned(
            left: 134.0,
            top: 598.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 15.0,
            child: PhysicalWidget6(),
          ),
          Positioned(
            left: 134.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 15.0,
            child: FlutLab1700Widget3(),
          ),
          Positioned(
            left: 134.0,
            top: 684.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 15.0,
            child: ScheduleWidget3(),
          ),
          Positioned(
            left: 134.0,
            top: 658.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 15.0,
            child: FlutLab1900Widget(),
          ),
          Positioned(
            left: 44.0,
            top: 598.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget9(),
          ),
          Positioned(
            left: 44.0,
            top: 628.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget11(),
          ),
          Positioned(
            left: 44.0,
            top: 658.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget5(),
          ),
          Positioned(
            left: 44.0,
            top: 688.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget5(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget21(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget9(),
          ),
          Positioned(
            left: 230.0,
            top: 727.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget20(),
          ),
          Positioned(
            left: 239.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 17.0,
            child: CreateClassWidget2(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget22(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget20(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget20(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget20(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget20(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget13(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget15(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget16(),
          ),
          Positioned(
            left: 137.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 101.0,
            height: 18.0,
            child: PabloGabrielWidget5(),
          ),
          Positioned(
            left: 116.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 34.0,
            child: MendezJimenezWidget5(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget9(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: SWidget2(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget10(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: StudentWidget3(),
          ),
          Positioned(
            left: 24.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 141.0,
            child: Rectangle45Widget(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle14Widget10(),
          ),
          Positioned(
            left: 131.0,
            top: 256.0,
            right: null,
            bottom: null,
            width: 114.0,
            height: 25.0,
            child: SessionLinkWidget1(),
          ),
          Positioned(
            left: 23.0,
            top: 288.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 26.0,
            child: Rectangle44Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 331.0,
            height: 38.0,
            child: Rectangle29Widget7(),
          ),
          Positioned(
            left: 323.0,
            top: 352.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon5Widget5(),
          ),
          Positioned(
            left: 145.0,
            top: 348.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 30.0,
            child: ResourcesWidget3(),
          ),
          Positioned(
            left: 87.0,
            top: 293.0,
            right: null,
            bottom: null,
            width: 202.0,
            height: 13.0,
            child: EnterthelinkofthevirtualsesionhereWidget(),
          ),
          Positioned(
            left: 37.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 257.0,
            height: 27.0,
            child: Rectangle46Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 440.0,
            right: null,
            bottom: null,
            width: 257.0,
            height: 27.0,
            child: Rectangle48Widget(),
          ),
          Positioned(
            left: 309.0,
            top: 397.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 27.0,
            child: Rectangle47Widget(),
          ),
          Positioned(
            left: 309.0,
            top: 440.0,
            right: null,
            bottom: null,
            width: 29.0,
            height: 27.0,
            child: Rectangle49Widget(),
          ),
          Positioned(
            left: 288.0,
            top: 420.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon6Widget2(),
          ),
          Positioned(
            left: 288.0,
            top: 463.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon7Widget2(),
          ),
          Positioned(
            left: 53.0,
            top: 404.0,
            right: null,
            bottom: null,
            width: 135.0,
            height: 13.0,
            child: SelectaWorddocumentWidget(),
          ),
          Positioned(
            left: 53.0,
            top: 447.0,
            right: null,
            bottom: null,
            width: 173.0,
            height: 13.0,
            child: SelectaPowertPointdocumentWidget(),
          )
        ]),
      ),
    ));
  }
}
