import 'package:flutter/material.dart';

/* Rectangle EE1 3
    Autogenerated by FlutLab FTF Generator
  */
class EE13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.0,
      height: 15.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/6dbf54035c34964d340c45e192c47713b057cbbd.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/6dbf54035c34964d340c45e192c47713b057cbbd.png",
          color: null,
          fit: BoxFit.cover,
          width: 15.0,
          height: 15.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
