import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Ellipse Ellipse 2
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse2Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 23.0,
      height: 23.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M23 11.5C23 17.8513 17.8513 23 11.5 23C5.14873 23 0 17.8513 0 11.5C0 5.14873 5.14873 0 11.5 0C17.8513 0 23 5.14873 23 11.5Z')
          ..color = Color.fromARGB(255, 18, 204, 253),
      ]),
    );
  }
}
