import 'package:flutter/material.dart';

/* Text Excellent teacher, he can learn a lot in his class, very good teaching service. I will recommend it to my friends.
    Autogenerated by FlutLab FTF Generator
  */
class ExcellentteacherhecanlearnalotinhisclassverygoodteachingserviceIwillrecommendittomyfriendsWidget1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Excellent teacher, he can learn a lot in his class, very good teaching service. I will recommend it to my friends.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
