import 'package:flutter/material.dart';

/* Text 4.6
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab46Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''4.6''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 1.171875,
        fontSize: 70.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
