import 'package:flutter/material.dart';

/* Text Sandoval Torres
    Autogenerated by FlutLab FTF Generator
  */
class SandovalTorresWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Sandoval Torres''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 10.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
