import 'package:flutter/material.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/BS1Widget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/EnteryourNameWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Rectangle4Widget2.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/StudentRegistrationWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/EnteryourPhoneWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Line4Widget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Rectangle2Widget2.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/BirthdateddmmaaWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/RegisterWidget3.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Rectangle1Widget3.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/BLogo1Widget3.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Line1Widget2.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/EnteryourDNIWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Line2Widget2.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Line5Widget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/RegisterWidget2.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Polygon3Widget1.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/EnteryourLastNameWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/EnteryourAddressWidget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Line3Widget1.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Line6Widget.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/Rectangle3Widget2.dart';
import 'package:flutterapp/figma/datastudentwidget/widgets/SigninWidget2.dart';

/* Frame Data Student
    Autogenerated by FlutLab FTF Generator
  */
class DataStudentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 323.0,
            child: BS1Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget3(),
          ),
          Positioned(
            left: 188.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget2(),
          ),
          Positioned(
            left: 73.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget2(),
          ),
          Positioned(
            left: 239.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget2(),
          ),
          Positioned(
            left: 0.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 653.0,
            child: Rectangle2Widget2(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo1Widget3(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle3Widget2(),
          ),
          Positioned(
            left: 153.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 21.0,
            child: RegisterWidget3(),
          ),
          Positioned(
            left: 38.0,
            top: 683.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line2Widget2(),
          ),
          Positioned(
            left: 38.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 117.0,
            height: 16.0,
            child: EnteryourAddressWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 600.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line1Widget2(),
          ),
          Positioned(
            left: 38.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 146.0,
            height: 16.0,
            child: BirthdateddmmaaWidget(),
          ),
          Positioned(
            left: 39.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 132.0037841796875,
            height: 0.0,
            child: Line3Widget1(),
          ),
          Positioned(
            left: 39.0,
            top: 493.0,
            right: null,
            bottom: null,
            width: 89.0,
            height: 16.0,
            child: EnteryourDNIWidget(),
          ),
          Positioned(
            left: 206.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 132.0037841796875,
            height: 0.0,
            child: Line6Widget(),
          ),
          Positioned(
            left: 206.0,
            top: 493.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 16.0,
            child: EnteryourPhoneWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 434.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line4Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 410.0,
            right: null,
            bottom: null,
            width: 134.0,
            height: 16.0,
            child: EnteryourLastNameWidget(),
          ),
          Positioned(
            left: 38.0,
            top: 351.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line5Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 327.0,
            right: null,
            bottom: null,
            width: 106.0,
            height: 16.0,
            child: EnteryourNameWidget(),
          ),
          Positioned(
            left: 35.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child:
                EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget(),
          ),
          Positioned(
            left: 98.0,
            top: 221.0,
            right: null,
            bottom: null,
            width: 181.0,
            height: 23.0,
            child: StudentRegistrationWidget(),
          ),
          Positioned(
            left: 336.0,
            top: 596.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: Polygon3Widget1(),
          )
        ]),
      ),
    ));
  }
}
