import 'package:flutter/material.dart';

/* Text classes
    Autogenerated by FlutLab FTF Generator
  */
class ClassesWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''classes''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 15.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 18, 204, 253),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
