import 'package:flutter/material.dart';

/* Text Course
    Autogenerated by FlutLab FTF Generator
  */
class CourseWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Course''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 20.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 14, 36, 220),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
