import 'package:flutter/material.dart';

/* Text Mathematics
    Autogenerated by FlutLab FTF Generator
  */
class MathematicsWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Mathematics''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 14, 36, 220),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
