import 'package:flutter/material.dart';

/* Text Schedule
    Autogenerated by FlutLab FTF Generator
  */
class ScheduleWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Schedule''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 25.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 14, 36, 220),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
