import 'package:flutter/material.dart';

/* Rectangle BPrincipal 1
    Autogenerated by FlutLab FTF Generator
  */
class BPrincipal1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 812.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/6742f4d420bcf946a253ab7bb810c74a1bc249db.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/6742f4d420bcf946a253ab7bb810c74a1bc249db.png",
          color: null,
          fit: BoxFit.cover,
          width: 375.0,
          height: 812.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
