import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/PhysicalWidget8.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle8Widget24.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/CreateWidget.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Ellipse4Widget18.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle29Widget9.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/BTH1Widget22.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/CourseWidget11.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle17Widget15.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle16Widget22.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle12Widget22.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/SessionLinkWidget3.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/BTP1Widget22.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle19Widget11.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/BTC1Widget22.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/TopicWidget8.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/StudentWidget5.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/MendezJimenezWidget7.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/FlutLab2Widget11.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/StatusWidget7.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/StartTimeWidget13.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/SWidget4.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/CreateClassWidget4.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/ScheduleWidget5.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/EndTimeWidget7.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Polygon5Widget7.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle10Widget23.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle14Widget12.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Httpsmrprofesorzoomus4578FG24DE58R63SF8Widget2.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/ClassDetailWidget8.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/HoursWidget12.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/FlutLab1700Widget5.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/FlutLab1900Widget2.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/ResourcesWidget5.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle13Widget22.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/PabloGabrielWidget7.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/SmoothLineMotionWidget2.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle9Widget23.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle18Widget17.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/ClassWidget11.dart';
import 'package:flutterapp/figma/teachersaveclasswidget/widgets/Rectangle44Widget3.dart';

/* Frame Teacher Save Class
    Autogenerated by FlutLab FTF Generator
  */
class TeacherSaveClassWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget23(),
          ),
          Positioned(
            left: 24.0,
            top: 408.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 213.0,
            child: Rectangle16Widget22(),
          ),
          Positioned(
            left: 45.0,
            top: 427.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 20.0,
            child: ClassDetailWidget8(),
          ),
          Positioned(
            left: 45.0,
            top: 462.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 15.0,
            child: TopicWidget8(),
          ),
          Positioned(
            left: 135.0,
            top: 462.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 15.0,
            child: SmoothLineMotionWidget2(),
          ),
          Positioned(
            left: 135.0,
            top: 492.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 15.0,
            child: PhysicalWidget8(),
          ),
          Positioned(
            left: 135.0,
            top: 522.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 15.0,
            child: FlutLab1700Widget5(),
          ),
          Positioned(
            left: 135.0,
            top: 578.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 15.0,
            child: ScheduleWidget5(),
          ),
          Positioned(
            left: 135.0,
            top: 552.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 15.0,
            child: FlutLab1900Widget2(),
          ),
          Positioned(
            left: 45.0,
            top: 492.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 15.0,
            child: CourseWidget11(),
          ),
          Positioned(
            left: 45.0,
            top: 522.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 15.0,
            child: StartTimeWidget13(),
          ),
          Positioned(
            left: 45.0,
            top: 552.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 15.0,
            child: EndTimeWidget7(),
          ),
          Positioned(
            left: 45.0,
            top: 582.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 15.0,
            child: StatusWidget7(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget23(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget11(),
          ),
          Positioned(
            left: 230.0,
            top: 727.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget22(),
          ),
          Positioned(
            left: 239.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 17.0,
            child: CreateClassWidget4(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget24(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget22(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget22(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget22(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget22(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle17Widget15(),
          ),
          Positioned(
            left: 23.0,
            top: -10.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 229.0,
            child: Rectangle18Widget17(),
          ),
          Positioned(
            left: 134.0,
            top: 48.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 108.0,
            child: Ellipse4Widget18(),
          ),
          Positioned(
            left: 137.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 101.0,
            height: 18.0,
            child: PabloGabrielWidget7(),
          ),
          Positioned(
            left: 116.0,
            top: 176.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 34.0,
            child: MendezJimenezWidget7(),
          ),
          Positioned(
            left: 283.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 17.0,
            height: 48.0,
            child: FlutLab2Widget11(),
          ),
          Positioned(
            left: 77.0,
            top: 81.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 48.0,
            child: SWidget4(),
          ),
          Positioned(
            left: 275.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 20.0,
            child: HoursWidget12(),
          ),
          Positioned(
            left: 61.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 20.0,
            child: StudentWidget5(),
          ),
          Positioned(
            left: 23.0,
            top: 249.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle14Widget12(),
          ),
          Positioned(
            left: 131.0,
            top: 256.0,
            right: null,
            bottom: null,
            width: 114.0,
            height: 25.0,
            child: SessionLinkWidget3(),
          ),
          Positioned(
            left: 23.0,
            top: 288.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 26.0,
            child: Rectangle44Widget3(),
          ),
          Positioned(
            left: 58.0,
            top: 293.0,
            right: null,
            bottom: null,
            width: 260.0,
            height: 13.0,
            child: Httpsmrprofesorzoomus4578FG24DE58R63SF8Widget2(),
          ),
          Positioned(
            left: 23.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 331.0,
            height: 38.0,
            child: Rectangle29Widget9(),
          ),
          Positioned(
            left: 343.0,
            top: 372.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon5Widget7(),
          ),
          Positioned(
            left: 145.0,
            top: 348.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 30.0,
            child: ResourcesWidget5(),
          ),
          Positioned(
            left: 23.0,
            top: 651.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 31.0,
            child: Rectangle19Widget11(),
          ),
          Positioned(
            left: 157.0,
            top: 658.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 18.0,
            child: CreateWidget(),
          )
        ]),
      ),
    ));
  }
}
