import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle11Widget12.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/PeriodicTableWidget2.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/MathematicsWidget13.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/HoursWidget8.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/GreatestCommomDivisorWidget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/F03Widget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab2403Widget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Ellipse3Widget4.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/ClassesWidget3.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle21Widget9.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle16Widget18.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle9Widget19.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/BTP1Widget18.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/ClassWidget7.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle19Widget9.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/LookatyourscheduledclassesWidget2.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/CreateClassWidget.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle12Widget18.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab2100Widget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab3103Widget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab1700Widget2.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/ChemistryWidget11.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/ScheduleWidget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/ChemistryWidget12.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/HistoryWidget9.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Q01Widget8.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab6Widget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Ellipse4Widget14.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab2503Widget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle13Widget18.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle20Widget9.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle10Widget19.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/MathematicsWidget14.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Ellipse2Widget4.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Line8Widget6.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/BTH1Widget18.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/CourseWidget7.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/ScheduledClassesWidget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/SecondWorldWarWidget3.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle8Widget20.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/BTC1Widget18.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Rectangle22Widget6.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab700Widget14.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/PhysicalWidget5.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/FlutLab3Widget2.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/ClassesMarchWidget1.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/Line9Widget3.dart';
import 'package:flutterapp/figma/teacherscheduledclasswidget/widgets/M01Widget5.dart';

/* Frame Teacher Scheduled Class
    Autogenerated by FlutLab FTF Generator
  */
class TeacherScheduledClassWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget19(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget19(),
          ),
          Positioned(
            left: 76.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 17.0,
            child: ClassWidget7(),
          ),
          Positioned(
            left: 41.0,
            top: 727.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget18(),
          ),
          Positioned(
            left: 239.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 87.0,
            height: 17.0,
            child: CreateClassWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget20(),
          ),
          Positioned(
            left: 277.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget18(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget18(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget18(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget18(),
          ),
          Positioned(
            left: 23.0,
            top: 285.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 299.0,
            child: Rectangle22Widget6(),
          ),
          Positioned(
            left: 44.0,
            top: 301.0,
            right: null,
            bottom: null,
            width: 77.0,
            height: 30.0,
            child: ScheduleWidget1(),
          ),
          Positioned(
            left: 245.0,
            top: 301.0,
            right: null,
            bottom: null,
            width: 11.0,
            height: 30.0,
            child: FlutLab6Widget1(),
          ),
          Positioned(
            left: 308.0,
            top: 301.0,
            right: null,
            bottom: null,
            width: 11.0,
            height: 30.0,
            child: FlutLab3Widget2(),
          ),
          Positioned(
            left: 45.0,
            top: 328.0,
            right: null,
            bottom: null,
            width: 77.0,
            height: 18.0,
            child: ClassesMarchWidget1(),
          ),
          Positioned(
            left: 236.0,
            top: 328.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 18.0,
            child: HoursWidget8(),
          ),
          Positioned(
            left: 294.0,
            top: 328.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 18.0,
            child: ClassesWidget3(),
          ),
          Positioned(
            left: 87.0,
            top: 451.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 15.0,
            child: PeriodicTableWidget2(),
          ),
          Positioned(
            left: 87.0,
            top: 468.0,
            right: null,
            bottom: null,
            width: 63.0,
            height: 16.0,
            child: ChemistryWidget11(),
          ),
          Positioned(
            left: 310.0,
            top: 451.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 18.0,
            child: FlutLab2503Widget1(),
          ),
          Positioned(
            left: 302.0,
            top: 469.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 18.0,
            child: FlutLab2100Widget1(),
          ),
          Positioned(
            left: 40.0,
            top: 374.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse2Widget4(),
          ),
          Positioned(
            left: 87.0,
            top: 375.0,
            right: null,
            bottom: null,
            width: 108.0,
            height: 15.0,
            child: SecondWorldWarWidget3(),
          ),
          Positioned(
            left: 87.0,
            top: 392.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 16.0,
            child: HistoryWidget9(),
          ),
          Positioned(
            left: 308.0,
            top: 375.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 18.0,
            child: FlutLab2403Widget1(),
          ),
          Positioned(
            left: 308.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 18.0,
            child: FlutLab700Widget14(),
          ),
          Positioned(
            left: 41.0,
            top: 524.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse4Widget14(),
          ),
          Positioned(
            left: 88.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 154.0,
            height: 15.0,
            child: GreatestCommomDivisorWidget1(),
          ),
          Positioned(
            left: 88.0,
            top: 542.0,
            right: null,
            bottom: null,
            width: 83.0,
            height: 16.0,
            child: MathematicsWidget13(),
          ),
          Positioned(
            left: 309.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 18.0,
            child: FlutLab3103Widget1(),
          ),
          Positioned(
            left: 301.0,
            top: 543.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 18.0,
            child: FlutLab1700Widget2(),
          ),
          Positioned(
            left: 38.0,
            top: 430.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line8Widget6(),
          ),
          Positioned(
            left: 40.0,
            top: 504.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line9Widget3(),
          ),
          Positioned(
            left: 41.0,
            top: 450.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse3Widget4(),
          ),
          Positioned(
            left: 23.0,
            top: -14.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 124.0,
            child: Rectangle16Widget18(),
          ),
          Positioned(
            left: 105.0,
            top: 79.0,
            right: null,
            bottom: null,
            width: 165.0,
            height: 13.0,
            child: LookatyourscheduledclassesWidget2(),
          ),
          Positioned(
            left: 23.0,
            top: 140.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 115.0,
            child: Rectangle11Widget12(),
          ),
          Positioned(
            left: 197.0,
            top: 179.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle19Widget9(),
          ),
          Positioned(
            left: 212.0,
            top: 224.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 13.0,
            child: PhysicalWidget5(),
          ),
          Positioned(
            left: 117.0,
            top: 179.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle20Widget9(),
          ),
          Positioned(
            left: 131.0,
            top: 187.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: Q01Widget8(),
          ),
          Positioned(
            left: 129.0,
            top: 224.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 13.0,
            child: ChemistryWidget12(),
          ),
          Positioned(
            left: 37.0,
            top: 179.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle21Widget9(),
          ),
          Positioned(
            left: 45.0,
            top: 224.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 13.0,
            child: MathematicsWidget14(),
          ),
          Positioned(
            left: 51.0,
            top: 187.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: M01Widget5(),
          ),
          Positioned(
            left: 164.0,
            top: 149.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 24.0,
            child: CourseWidget7(),
          ),
          Positioned(
            left: 80.0,
            top: 41.0,
            right: null,
            bottom: null,
            width: 219.0,
            height: 42.0,
            child: ScheduledClassesWidget1(),
          ),
          Positioned(
            left: 211.0,
            top: 187.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: F03Widget1(),
          )
        ]),
      ),
    ));
  }
}
