import 'package:flutter/material.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle8Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourDNIWidget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line2Widget5.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle2Widget6.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line11Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/RegisterWidget10.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line8Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line12Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/RegisterWidget7.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/BLogo2Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/SigninWidget6.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget3.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourPhoneWidget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line7Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle5Widget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle1Widget7.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line6Widget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourLastNameWidget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourAddressWidget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/SigninWidget7.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/RegisterWidget9.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/BirthdateddmmaaWidget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourNameWidget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/TeacherRegistrationWidget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line1Widget4.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Polygon3Widget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line9Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourLastNameWidget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line10Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourAddressWidget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line4Widget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/BLogo1Widget6.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle4Widget6.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle6Widget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/RegisterWidget8.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourPhoneWidget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/BirthdateddmmaaWidget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line3Widget4.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle7Widget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/BT2Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourDNIWidget2.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Rectangle3Widget6.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/TeacherRegistrationWidget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/BT1Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Polygon4Widget.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/EnteryourNameWidget1.dart';
import 'package:flutterapp/figma/datateacherwidget/widgets/Line5Widget2.dart';

/* Frame Data Teacher
    Autogenerated by FlutLab FTF Generator
  */
class DataTeacherWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 323.0,
            child: BT1Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle1Widget7(),
          ),
          Positioned(
            left: 188.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle4Widget6(),
          ),
          Positioned(
            left: 73.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget6(),
          ),
          Positioned(
            left: 239.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget7(),
          ),
          Positioned(
            left: 0.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 653.0,
            child: Rectangle2Widget6(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo1Widget6(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle3Widget6(),
          ),
          Positioned(
            left: 153.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 21.0,
            child: RegisterWidget8(),
          ),
          Positioned(
            left: 38.0,
            top: 683.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line2Widget5(),
          ),
          Positioned(
            left: 38.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 117.0,
            height: 16.0,
            child: EnteryourAddressWidget1(),
          ),
          Positioned(
            left: 38.0,
            top: 600.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line1Widget4(),
          ),
          Positioned(
            left: 38.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 146.0,
            height: 16.0,
            child: BirthdateddmmaaWidget1(),
          ),
          Positioned(
            left: 39.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 132.0037841796875,
            height: 0.0,
            child: Line3Widget4(),
          ),
          Positioned(
            left: 39.0,
            top: 493.0,
            right: null,
            bottom: null,
            width: 89.0,
            height: 16.0,
            child: EnteryourDNIWidget1(),
          ),
          Positioned(
            left: 206.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 132.0037841796875,
            height: 0.0,
            child: Line6Widget2(),
          ),
          Positioned(
            left: 206.0,
            top: 493.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 16.0,
            child: EnteryourPhoneWidget1(),
          ),
          Positioned(
            left: 38.0,
            top: 434.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line4Widget2(),
          ),
          Positioned(
            left: 37.0,
            top: 410.0,
            right: null,
            bottom: null,
            width: 134.0,
            height: 16.0,
            child: EnteryourLastNameWidget1(),
          ),
          Positioned(
            left: 38.0,
            top: 351.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line5Widget2(),
          ),
          Positioned(
            left: 38.0,
            top: 327.0,
            right: null,
            bottom: null,
            width: 106.0,
            height: 16.0,
            child: EnteryourNameWidget1(),
          ),
          Positioned(
            left: 35.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child:
                EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget2(),
          ),
          Positioned(
            left: 95.0,
            top: 221.0,
            right: null,
            bottom: null,
            width: 187.0,
            height: 23.0,
            child: TeacherRegistrationWidget(),
          ),
          Positioned(
            left: 336.0,
            top: 596.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: Polygon3Widget2(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 323.0,
            child: BT2Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle5Widget2(),
          ),
          Positioned(
            left: 188.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 46.0,
            child: Rectangle6Widget1(),
          ),
          Positioned(
            left: 73.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 18.0,
            child: SigninWidget7(),
          ),
          Positioned(
            left: 239.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: RegisterWidget9(),
          ),
          Positioned(
            left: 0.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 653.0,
            child: Rectangle7Widget1(),
          ),
          Positioned(
            left: 148.0,
            top: 52.0,
            right: null,
            bottom: null,
            width: 76.0,
            height: 74.90643310546875,
            child: BLogo2Widget(),
          ),
          Positioned(
            left: 35.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 39.0,
            child: Rectangle8Widget(),
          ),
          Positioned(
            left: 153.0,
            top: 747.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 21.0,
            child: RegisterWidget10(),
          ),
          Positioned(
            left: 38.0,
            top: 683.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line7Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 117.0,
            height: 16.0,
            child: EnteryourAddressWidget2(),
          ),
          Positioned(
            left: 38.0,
            top: 600.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line8Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 146.0,
            height: 16.0,
            child: BirthdateddmmaaWidget2(),
          ),
          Positioned(
            left: 39.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 132.0037841796875,
            height: 0.0,
            child: Line9Widget(),
          ),
          Positioned(
            left: 39.0,
            top: 493.0,
            right: null,
            bottom: null,
            width: 89.0,
            height: 16.0,
            child: EnteryourDNIWidget2(),
          ),
          Positioned(
            left: 206.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 132.0037841796875,
            height: 0.0,
            child: Line10Widget(),
          ),
          Positioned(
            left: 206.0,
            top: 493.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 16.0,
            child: EnteryourPhoneWidget2(),
          ),
          Positioned(
            left: 38.0,
            top: 434.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line11Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 410.0,
            right: null,
            bottom: null,
            width: 134.0,
            height: 16.0,
            child: EnteryourLastNameWidget2(),
          ),
          Positioned(
            left: 38.0,
            top: 351.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line12Widget(),
          ),
          Positioned(
            left: 38.0,
            top: 327.0,
            right: null,
            bottom: null,
            width: 106.0,
            height: 16.0,
            child: EnteryourNameWidget2(),
          ),
          Positioned(
            left: 35.0,
            top: 255.0,
            right: null,
            bottom: null,
            width: 306.0,
            height: 32.0,
            child:
                EnteryourpersonaldataintheestablishedfieldsforyourregistrationWidget3(),
          ),
          Positioned(
            left: 95.0,
            top: 221.0,
            right: null,
            bottom: null,
            width: 187.0,
            height: 23.0,
            child: TeacherRegistrationWidget1(),
          ),
          Positioned(
            left: 336.0,
            top: 596.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: Polygon4Widget(),
          )
        ]),
      ),
    ));
  }
}
