import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/SelectaTimeWidget1.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/M01Widget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle19Widget6.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle9Widget13.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/FastClassWidget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/NotificationsWidget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle13Widget12.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/FlutLab450Widget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/TutoFastWidget4.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/StartTimeWidget8.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/N21Widget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/SelectCourseTopicWidget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle16Widget12.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/BTP1Widget12.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/HWidget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle20Widget6.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle8Widget14.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/BTC1Widget12.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/IdealSafeandReliableWidget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/TeachingHoursWidget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle17Widget9.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/F02Widget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/TopictoStudyWidget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/FindyourtutoringWidget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/MathematicsWidget7.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle10Widget13.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/HoursrepresentpaypermonthWidget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/SearchWidget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Q01Widget5.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle14Widget6.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/SelecttheDateWidget.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/BTH1Widget12.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Ellipse4Widget9.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle21Widget6.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle12Widget12.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/PhysicalWidget2.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/ChemistryWidget8.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle11Widget7.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Line7Widget4.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/AssignedDateWidget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/Rectangle15Widget3.dart';
import 'package:flutterapp/figma/teacherdashboardwidget/widgets/ChoosetheCourseWidget3.dart';

/* Frame Teacher Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class TeacherDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget13(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget13(),
          ),
          Positioned(
            left: 60.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 17.0,
            child: FastClassWidget3(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget12(),
          ),
          Positioned(
            left: 240.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 17.0,
            child: NotificationsWidget3(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget14(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget12(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget12(),
          ),
          Positioned(
            left: 168.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget12(),
          ),
          Positioned(
            left: 23.0,
            top: 567.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 115.0,
            child: Rectangle11Widget7(),
          ),
          Positioned(
            left: 37.0,
            top: 577.0,
            right: null,
            bottom: null,
            width: 110.0,
            height: 16.0,
            child: ChoosetheCourseWidget3(),
          ),
          Positioned(
            left: 197.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle19Widget6(),
          ),
          Positioned(
            left: 212.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 13.0,
            child: PhysicalWidget2(),
          ),
          Positioned(
            left: 117.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle20Widget6(),
          ),
          Positioned(
            left: 131.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: Q01Widget5(),
          ),
          Positioned(
            left: 129.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 13.0,
            child: ChemistryWidget8(),
          ),
          Positioned(
            left: 37.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle21Widget6(),
          ),
          Positioned(
            left: 45.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 13.0,
            child: MathematicsWidget7(),
          ),
          Positioned(
            left: 51.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: M01Widget3(),
          ),
          Positioned(
            left: 23.0,
            top: 358.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 179.0,
            child: Rectangle16Widget12(),
          ),
          Positioned(
            left: 131.0,
            top: 501.0,
            right: null,
            bottom: null,
            width: 115.0,
            height: 15.0,
            child: SelectCourseTopicWidget(),
          ),
          Positioned(
            left: 144.0,
            top: 476.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 17.0,
            child: TopictoStudyWidget3(),
          ),
          Positioned(
            left: 218.0,
            top: 418.0,
            right: null,
            bottom: null,
            width: 99.0,
            height: 17.0,
            child: AssignedDateWidget3(),
          ),
          Positioned(
            left: 223.0,
            top: 443.0,
            right: null,
            bottom: null,
            width: 91.0,
            height: 15.0,
            child: SelecttheDateWidget(),
          ),
          Positioned(
            left: 69.0,
            top: 445.0,
            right: null,
            bottom: null,
            width: 78.0,
            height: 15.0,
            child: SelectaTimeWidget1(),
          ),
          Positioned(
            left: 76.0,
            top: 418.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 17.0,
            child: StartTimeWidget8(),
          ),
          Positioned(
            left: 188.0,
            top: 421.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 0.0,
            child: Line7Widget4(),
          ),
          Positioned(
            left: 37.0,
            top: 371.0,
            right: null,
            bottom: null,
            width: 302.0,
            height: 30.0,
            child: Rectangle17Widget9(),
          ),
          Positioned(
            left: 163.0,
            top: 377.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 18.0,
            child: SearchWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle15Widget3(),
          ),
          Positioned(
            left: 55.0,
            top: 274.0,
            right: null,
            bottom: null,
            width: 49.0,
            height: 48.0,
            child: FlutLab450Widget(),
          ),
          Positioned(
            left: 107.0,
            top: 280.0,
            right: null,
            bottom: null,
            width: 19.0,
            height: 37.0,
            child: HWidget3(),
          ),
          Positioned(
            left: 144.0,
            top: 277.0,
            right: null,
            bottom: null,
            width: 127.0,
            height: 21.0,
            child: TeachingHoursWidget(),
          ),
          Positioned(
            left: 144.0,
            top: 299.0,
            right: null,
            bottom: null,
            width: 166.0,
            height: 13.0,
            child: HoursrepresentpaypermonthWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 141.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 93.0,
            child: Rectangle14Widget6(),
          ),
          Positioned(
            left: 42.0,
            top: 186.0,
            right: null,
            bottom: null,
            width: 262.0,
            height: 40.0,
            child: IdealSafeandReliableWidget3(),
          ),
          Positioned(
            left: 42.0,
            top: 170.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 19.0,
            child: FindyourtutoringWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 61.0,
            child: TutoFastWidget4(),
          ),
          Positioned(
            left: 211.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: F02Widget(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget12(),
          ),
          Positioned(
            left: 276.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 28.81999969482422,
            height: 35.0,
            child: N21Widget(),
          ),
          Positioned(
            left: 318.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse4Widget9(),
          )
        ]),
      ),
    ));
  }
}
