import 'package:flutter/material.dart';

/* Rectangle AD 1
    Autogenerated by FlutLab FTF Generator
  */
class AD1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 34.0,
      height: 34.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/75b4d73b5c0ed822e17d9b9491874cac4ddf2f5f.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/75b4d73b5c0ed822e17d9b9491874cac4ddf2f5f.png",
          color: null,
          fit: BoxFit.cover,
          width: 34.0,
          height: 34.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
