import 'package:flutter/material.dart';

/* Rectangle CN 1
    Autogenerated by FlutLab FTF Generator
  */
class CN1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 30.0,
      height: 30.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/b3159cf8bac37686f3a2dfe6844efd42bbde8721.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/b3159cf8bac37686f3a2dfe6844efd42bbde8721.png",
          color: null,
          fit: BoxFit.cover,
          width: 30.0,
          height: 30.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
