import 'package:flutter/material.dart';

/* Rectangle EQ1 1
    Autogenerated by FlutLab FTF Generator
  */
class EQ11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 30.0,
      height: 30.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/70cb00c90a703bb4418e514925a7c7b3fcd3b7f4.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/70cb00c90a703bb4418e514925a7c7b3fcd3b7f4.png",
          color: null,
          fit: BoxFit.cover,
          width: 30.0,
          height: 30.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
