import 'package:flutter/material.dart';

/* Text Quiroz Risopatron
    Autogenerated by FlutLab FTF Generator
  */
class QuirozRisopatronWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Quiroz Risopatron''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 28.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
