import 'package:flutter/material.dart';

/* Text Urb. Caman 789
    Autogenerated by FlutLab FTF Generator
  */
class UrbCaman789Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Urb. Caman 789''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
