import 'package:flutter/material.dart';

/* Text Enter your Session here
    Autogenerated by FlutLab FTF Generator
  */
class EnteryourSessionhereWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Enter your Session here''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 20.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
