import 'package:flutter/material.dart';

/* Text This button redirects you to the session of your class
    Autogenerated by FlutLab FTF Generator
  */
class ThisbuttonredirectsyoutothesessionofyourclassWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''This button redirects you to the session of your class''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
