import 'package:flutter/material.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/BTH1Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/IdealSafeandReliableWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle19Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/FastClassWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Line7Widget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/N11Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle20Widget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle14Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/ReserveWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle13Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/StartTimeWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/CreditWidget2.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/OtherWidget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle11Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/ChemistryWidget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/HWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/ChoosetheCourseWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/H01Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/MathematicsWidget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/BTC1Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Ellipse1Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle21Widget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Q01Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/FlutLab250Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle17Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle9Widget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Aclassrequiresaminimum2hoursWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/HistoryWidget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle8Widget2.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/SelectaTimeWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle18Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle12Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/BTP1Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/WritethetopictostudyduringthesessionWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/TutoFastWidget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/FindyourtutorWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle10Widget1.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle15Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/NotificationsWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/TopictoStudyWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/M01Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/Rectangle16Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/AddtheDateWidget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/O01Widget.dart';
import 'package:flutterapp/figma/studentdashboardwidget/widgets/AssignedDateWidget.dart';

/* Frame Student Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class StudentDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget1(),
          ),
          Positioned(
            left: 60.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 17.0,
            child: FastClassWidget(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget(),
          ),
          Positioned(
            left: 240.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 17.0,
            child: NotificationsWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget2(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget(),
          ),
          Positioned(
            left: 168.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget(),
          ),
          Positioned(
            left: 23.0,
            top: 567.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 115.0,
            child: Rectangle11Widget(),
          ),
          Positioned(
            left: 277.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle18Widget(),
          ),
          Positioned(
            left: 297.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 13.0,
            child: OtherWidget1(),
          ),
          Positioned(
            left: 291.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: O01Widget(),
          ),
          Positioned(
            left: 197.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle19Widget(),
          ),
          Positioned(
            left: 209.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 13.0,
            child: ChemistryWidget1(),
          ),
          Positioned(
            left: 211.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: Q01Widget(),
          ),
          Positioned(
            left: 117.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle20Widget1(),
          ),
          Positioned(
            left: 134.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 28.0,
            height: 13.0,
            child: HistoryWidget1(),
          ),
          Positioned(
            left: 132.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: H01Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 602.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle21Widget1(),
          ),
          Positioned(
            left: 45.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 13.0,
            child: MathematicsWidget1(),
          ),
          Positioned(
            left: 51.0,
            top: 610.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: M01Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 577.0,
            right: null,
            bottom: null,
            width: 110.0,
            height: 16.0,
            child: ChoosetheCourseWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 141.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 93.0,
            child: Rectangle14Widget(),
          ),
          Positioned(
            left: 42.0,
            top: 186.0,
            right: null,
            bottom: null,
            width: 262.0,
            height: 40.0,
            child: IdealSafeandReliableWidget(),
          ),
          Positioned(
            left: 42.0,
            top: 170.0,
            right: null,
            bottom: null,
            width: 107.0,
            height: 19.0,
            child: FindyourtutorWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 61.0,
            child: TutoFastWidget1(),
          ),
          Positioned(
            left: 318.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse1Widget(),
          ),
          Positioned(
            left: 276.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 28.823530197143555,
            height: 35.0,
            child: N11Widget(),
          ),
          Positioned(
            left: 23.0,
            top: 358.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 179.0,
            child: Rectangle16Widget(),
          ),
          Positioned(
            left: 68.0,
            top: 501.0,
            right: null,
            bottom: null,
            width: 240.0,
            height: 15.0,
            child: WritethetopictostudyduringthesessionWidget(),
          ),
          Positioned(
            left: 140.0,
            top: 476.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 17.0,
            child: TopictoStudyWidget(),
          ),
          Positioned(
            left: 218.0,
            top: 418.0,
            right: null,
            bottom: null,
            width: 99.0,
            height: 17.0,
            child: AssignedDateWidget(),
          ),
          Positioned(
            left: 228.0,
            top: 443.0,
            right: null,
            bottom: null,
            width: 81.0,
            height: 15.0,
            child: AddtheDateWidget(),
          ),
          Positioned(
            left: 69.0,
            top: 445.0,
            right: null,
            bottom: null,
            width: 78.0,
            height: 15.0,
            child: SelectaTimeWidget(),
          ),
          Positioned(
            left: 76.0,
            top: 418.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 17.0,
            child: StartTimeWidget(),
          ),
          Positioned(
            left: 187.0,
            top: 421.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 0.0,
            child: Line7Widget1(),
          ),
          Positioned(
            left: 37.0,
            top: 371.0,
            right: null,
            bottom: null,
            width: 302.0,
            height: 30.0,
            child: Rectangle17Widget(),
          ),
          Positioned(
            left: 158.0,
            top: 377.0,
            right: null,
            bottom: null,
            width: 58.0,
            height: 18.0,
            child: ReserveWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 64.0,
            child: Rectangle15Widget(),
          ),
          Positioned(
            left: 55.0,
            top: 274.0,
            right: null,
            bottom: null,
            width: 49.0,
            height: 48.0,
            child: FlutLab250Widget(),
          ),
          Positioned(
            left: 107.0,
            top: 280.0,
            right: null,
            bottom: null,
            width: 19.0,
            height: 37.0,
            child: HWidget(),
          ),
          Positioned(
            left: 144.0,
            top: 277.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 21.0,
            child: CreditWidget2(),
          ),
          Positioned(
            left: 144.0,
            top: 299.0,
            right: null,
            bottom: null,
            width: 184.0,
            height: 13.0,
            child: Aclassrequiresaminimum2hoursWidget(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget(),
          )
        ]),
      ),
    ));
  }
}
