import 'package:flutter/material.dart';

/* Text Hours
    Autogenerated by FlutLab FTF Generator
  */
class HoursWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Hours''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 17.0,
        fontFamily: 'Bebas Neue',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
