import 'package:flutter/material.dart';

/* Text https://mrprofesor.zoom.us/4578FG24DE58R63SF8
    Autogenerated by FlutLab FTF Generator
  */
class Httpsmrprofesorzoomus4578FG24DE58R63SF8Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''https://mrprofesor.zoom.us/4578FG24DE58R63SF8''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
