import 'package:flutter/material.dart';

/* Text Physical_SmoothLineMotion.doc
    Autogenerated by FlutLab FTF Generator
  */
class Physical_SmoothLineMotiondocWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Physical_SmoothLineMotion.doc''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 18, 204, 253),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
