import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle23Widget2.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/BTH1Widget14.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Ellipse4Widget11.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/N21Widget2.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/MathematicsWidget11.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/ApplyWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/BackWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/MendezJimenezPabloGabrielWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/StudentNamesWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/StudentDataWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/BTC1Widget14.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle8Widget16.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle25Widget5.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/BTP1Widget14.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle10Widget15.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle13Widget14.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/NotificationsWidget5.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle16Widget14.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/CourseoftheSessionWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle24Widget2.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/SessionDataWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle9Widget15.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/StudentsLastNameWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/PabloGabrielWidget2.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/FlutLab76452369Widget1.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/TutoFastWidget6.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/ClassRequestWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/QuadraticMultiplicationWidget1.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/FlutLab700Widget13.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/FastClassWidget5.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/SessionTopicWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/MendezJimenezWidget2.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle11Widget9.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/DNIWidget1.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/SessionStartTimeWidget.dart';
import 'package:flutterapp/figma/teacherpostulationwidget/widgets/Rectangle12Widget14.dart';

/* Frame Teacher Postulation
    Autogenerated by FlutLab FTF Generator
  */
class TeacherPostulationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget15(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget15(),
          ),
          Positioned(
            left: 60.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 17.0,
            child: FastClassWidget5(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget14(),
          ),
          Positioned(
            left: 240.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 17.0,
            child: NotificationsWidget5(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget16(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget14(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget14(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget14(),
          ),
          Positioned(
            left: 168.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget14(),
          ),
          Positioned(
            left: 23.0,
            top: 405.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 152.0,
            child: Rectangle11Widget9(),
          ),
          Positioned(
            left: 24.0,
            top: 587.0,
            right: null,
            bottom: null,
            width: 154.0,
            height: 33.0,
            child: Rectangle24Widget2(),
          ),
          Positioned(
            left: 199.0,
            top: 587.0,
            right: null,
            bottom: null,
            width: 154.0,
            height: 33.0,
            child: Rectangle25Widget5(),
          ),
          Positioned(
            left: 23.0,
            top: 182.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 193.0,
            child: Rectangle16Widget14(),
          ),
          Positioned(
            left: 41.0,
            top: 197.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 20.0,
            child: StudentDataWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 423.0,
            right: null,
            bottom: null,
            width: 98.0,
            height: 20.0,
            child: SessionDataWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 61.0,
            child: TutoFastWidget6(),
          ),
          Positioned(
            left: 23.0,
            top: 141.0,
            right: null,
            bottom: null,
            width: 141.0,
            height: 26.0,
            child: ClassRequestWidget(),
          ),
          Positioned(
            left: 87.0,
            top: 235.0,
            right: null,
            bottom: null,
            width: 201.0,
            height: 16.0,
            child: MendezJimenezPabloGabrielWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 279.0,
            right: null,
            bottom: null,
            width: 117.0,
            height: 15.0,
            child: StudentsLastNameWidget(),
          ),
          Positioned(
            left: 189.0,
            top: 279.0,
            right: null,
            bottom: null,
            width: 99.0,
            height: 15.0,
            child: MendezJimenezWidget2(),
          ),
          Positioned(
            left: 189.0,
            top: 309.0,
            right: null,
            bottom: null,
            width: 81.0,
            height: 15.0,
            child: PabloGabrielWidget2(),
          ),
          Positioned(
            left: 189.0,
            top: 339.0,
            right: null,
            bottom: null,
            width: 54.0,
            height: 15.0,
            child: FlutLab76452369Widget1(),
          ),
          Positioned(
            left: 44.0,
            top: 309.0,
            right: null,
            bottom: null,
            width: 88.0,
            height: 15.0,
            child: StudentNamesWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 339.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 15.0,
            child: DNIWidget1(),
          ),
          Positioned(
            left: 44.0,
            top: 458.0,
            right: null,
            bottom: null,
            width: 77.0,
            height: 15.0,
            child: SessionTopicWidget(),
          ),
          Positioned(
            left: 189.0,
            top: 458.0,
            right: null,
            bottom: null,
            width: 142.0,
            height: 15.0,
            child: QuadraticMultiplicationWidget1(),
          ),
          Positioned(
            left: 189.0,
            top: 488.0,
            right: null,
            bottom: null,
            width: 77.0,
            height: 15.0,
            child: MathematicsWidget11(),
          ),
          Positioned(
            left: 189.0,
            top: 518.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget13(),
          ),
          Positioned(
            left: 44.0,
            top: 488.0,
            right: null,
            bottom: null,
            width: 123.0,
            height: 15.0,
            child: CourseoftheSessionWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 518.0,
            right: null,
            bottom: null,
            width: 102.0,
            height: 15.0,
            child: SessionStartTimeWidget(),
          ),
          Positioned(
            left: 37.0,
            top: 226.0,
            right: null,
            bottom: null,
            width: 302.0,
            height: 35.0,
            child: Rectangle23Widget2(),
          ),
          Positioned(
            left: 84.0,
            top: 595.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 18.0,
            child: BackWidget(),
          ),
          Positioned(
            left: 254.0,
            top: 595.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 18.0,
            child: ApplyWidget(),
          ),
          Positioned(
            left: 276.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 28.81999969482422,
            height: 35.0,
            child: N21Widget2(),
          ),
          Positioned(
            left: 318.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse4Widget11(),
          )
        ]),
      ),
    ));
  }
}
