import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/ChoosetheCourseWidget4.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/BTH1Widget13.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/NotificationsWidget4.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Ellipse4Widget10.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/LunesWidget.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/MathematicsWidget10.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/BTP1Widget13.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle9Widget14.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/QuadraticMultiplicationWidget.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/ResultsWidget.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle16Widget13.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/StartTimeWidget9.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Line7Widget5.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/MathematicsWidget9.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/FlutLab700Widget11.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle10Widget14.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/FlutLab700Widget10.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/N21Widget1.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/ChemistryWidget9.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle22Widget3.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/F02Widget1.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/SerpaTrinidadWidget.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle20Widget7.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/DanielWidget.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Ellipse2Widget2.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Ellipse3Widget2.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/PhysicalWidget3.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/MathematicsWidget8.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/TopictoStudyWidget4.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/FastClassWidget4.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle13Widget13.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/SearchWidget1.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Q01Widget6.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle21Widget7.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/TutoFastWidget5.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/AssignedDateWidget4.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle8Widget15.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/FlutLab700Widget12.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle11Widget8.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/BTC1Widget13.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/M11Widget2.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/BautistaSchwarengsWidget.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle19Widget7.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle12Widget13.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Rectangle17Widget10.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/SofiaWidget.dart';
import 'package:flutterapp/figma/teachersearchwidget/widgets/Line8Widget4.dart';

/* Frame Teacher Search
    Autogenerated by FlutLab FTF Generator
  */
class TeacherSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget14(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget14(),
          ),
          Positioned(
            left: 60.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 66.0,
            height: 17.0,
            child: FastClassWidget4(),
          ),
          Positioned(
            left: 40.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget13(),
          ),
          Positioned(
            left: 240.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 84.0,
            height: 17.0,
            child: NotificationsWidget4(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget15(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget13(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget13(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget13(),
          ),
          Positioned(
            left: 168.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget13(),
          ),
          Positioned(
            left: 23.0,
            top: 495.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 188.0,
            child: Rectangle22Widget3(),
          ),
          Positioned(
            left: 39.0,
            top: 507.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 29.0,
            child: ResultsWidget(),
          ),
          Positioned(
            left: 41.0,
            top: 551.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse2Widget2(),
          ),
          Positioned(
            left: 88.0,
            top: 549.0,
            right: null,
            bottom: null,
            width: 41.0,
            height: 16.0,
            child: DanielWidget(),
          ),
          Positioned(
            left: 88.0,
            top: 570.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 16.0,
            child: BautistaSchwarengsWidget(),
          ),
          Positioned(
            left: 249.0,
            top: 546.0,
            right: null,
            bottom: null,
            width: 83.0,
            height: 16.0,
            child: MathematicsWidget8(),
          ),
          Positioned(
            left: 305.0,
            top: 570.0,
            right: null,
            bottom: null,
            width: 26.0,
            height: 16.0,
            child: FlutLab700Widget10(),
          ),
          Positioned(
            left: 39.0,
            top: 607.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 0.0,
            child: Line8Widget4(),
          ),
          Positioned(
            left: 42.0,
            top: 627.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse3Widget2(),
          ),
          Positioned(
            left: 89.0,
            top: 625.0,
            right: null,
            bottom: null,
            width: 31.0,
            height: 16.0,
            child: SofiaWidget(),
          ),
          Positioned(
            left: 89.0,
            top: 646.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 16.0,
            child: SerpaTrinidadWidget(),
          ),
          Positioned(
            left: 250.0,
            top: 622.0,
            right: null,
            bottom: null,
            width: 83.0,
            height: 16.0,
            child: MathematicsWidget9(),
          ),
          Positioned(
            left: 306.0,
            top: 646.0,
            right: null,
            bottom: null,
            width: 26.0,
            height: 16.0,
            child: FlutLab700Widget11(),
          ),
          Positioned(
            left: 23.0,
            top: 350.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 115.0,
            child: Rectangle11Widget8(),
          ),
          Positioned(
            left: 197.0,
            top: 385.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle19Widget7(),
          ),
          Positioned(
            left: 212.0,
            top: 430.0,
            right: null,
            bottom: null,
            width: 32.0,
            height: 13.0,
            child: PhysicalWidget3(),
          ),
          Positioned(
            left: 117.0,
            top: 385.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle20Widget7(),
          ),
          Positioned(
            left: 132.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: Q01Widget6(),
          ),
          Positioned(
            left: 129.0,
            top: 430.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 13.0,
            child: ChemistryWidget9(),
          ),
          Positioned(
            left: 37.0,
            top: 385.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 62.0,
            child: Rectangle21Widget7(),
          ),
          Positioned(
            left: 45.0,
            top: 430.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 13.0,
            child: MathematicsWidget10(),
          ),
          Positioned(
            left: 51.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: M11Widget2(),
          ),
          Positioned(
            left: 37.0,
            top: 360.0,
            right: null,
            bottom: null,
            width: 110.0,
            height: 16.0,
            child: ChoosetheCourseWidget4(),
          ),
          Positioned(
            left: 23.0,
            top: 141.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 179.0,
            child: Rectangle16Widget13(),
          ),
          Positioned(
            left: 117.0,
            top: 284.0,
            right: null,
            bottom: null,
            width: 142.0,
            height: 15.0,
            child: QuadraticMultiplicationWidget(),
          ),
          Positioned(
            left: 144.0,
            top: 259.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 17.0,
            child: TopictoStudyWidget4(),
          ),
          Positioned(
            left: 218.0,
            top: 201.0,
            right: null,
            bottom: null,
            width: 99.0,
            height: 17.0,
            child: AssignedDateWidget4(),
          ),
          Positioned(
            left: 252.0,
            top: 226.0,
            right: null,
            bottom: null,
            width: 33.0,
            height: 15.0,
            child: LunesWidget(),
          ),
          Positioned(
            left: 96.0,
            top: 228.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 15.0,
            child: FlutLab700Widget12(),
          ),
          Positioned(
            left: 76.0,
            top: 201.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 17.0,
            child: StartTimeWidget9(),
          ),
          Positioned(
            left: 188.0,
            top: 204.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 0.0,
            child: Line7Widget5(),
          ),
          Positioned(
            left: 37.0,
            top: 154.0,
            right: null,
            bottom: null,
            width: 302.0,
            height: 30.0,
            child: Rectangle17Widget10(),
          ),
          Positioned(
            left: 163.0,
            top: 160.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 18.0,
            child: SearchWidget1(),
          ),
          Positioned(
            left: 23.0,
            top: 57.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 61.0,
            child: TutoFastWidget5(),
          ),
          Positioned(
            left: 211.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 34.0,
            height: 34.0,
            child: F02Widget1(),
          ),
          Positioned(
            left: 276.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 28.81999969482422,
            height: 35.0,
            child: N21Widget1(),
          ),
          Positioned(
            left: 318.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: Ellipse4Widget10(),
          )
        ]),
      ),
    ));
  }
}
