import 'package:flutter/material.dart';

/* Text Enter the data in the established fields and select a category.
    Autogenerated by FlutLab FTF Generator
  */
class EnterthedataintheestablishedfieldsandselectacategoryWidget1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Enter the data in the established fields and select a category.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
