import 'package:flutter/material.dart';

/* Rectangle PM 1
    Autogenerated by FlutLab FTF Generator
  */
class PM1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.0,
      height: 128.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/138274a822135ed3120771322fc810931e8b5d2e.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/138274a822135ed3120771322fc810931e8b5d2e.png",
          color: null,
          fit: BoxFit.cover,
          width: 80.0,
          height: 128.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
