import 'package:flutter/material.dart';

/* Rectangle PW 1
    Autogenerated by FlutLab FTF Generator
  */
class PW1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.0,
      height: 128.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/2b2003f869f16b88cbfe22f1bd2fcc16dffc7131.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/2b2003f869f16b88cbfe22f1bd2fcc16dffc7131.png",
          color: null,
          fit: BoxFit.cover,
          width: 80.0,
          height: 128.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
