import 'package:flutter/material.dart';

/* Rectangle BLogo 1
    Autogenerated by FlutLab FTF Generator
  */
class BLogo1Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 76.0,
      height: 74.90643310546875,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/316e42d5430cfa051adc93f86d1dcb369e2fb844.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/316e42d5430cfa051adc93f86d1dcb369e2fb844.png",
          color: null,
          fit: BoxFit.cover,
          width: 76.0,
          height: 74.90643310546875,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
