import 'package:flutter/material.dart';

/* Rectangle EM 1
    Autogenerated by FlutLab FTF Generator
  */
class EM1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.0,
      height: 128.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/c78a8b3126faa912b13013b8e2d6e98446862dbd.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/c78a8b3126faa912b13013b8e2d6e98446862dbd.png",
          color: null,
          fit: BoxFit.cover,
          width: 80.0,
          height: 128.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
