import 'package:flutter/material.dart';

/* Rectangle EW 1
    Autogenerated by FlutLab FTF Generator
  */
class EW1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.0,
      height: 128.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/ca738465d2dbc3cefd09d74f5d457518bd0d5cda.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/ca738465d2dbc3cefd09d74f5d457518bd0d5cda.png",
          color: null,
          fit: BoxFit.cover,
          width: 80.0,
          height: 128.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
