import 'package:flutter/material.dart';

/* Text Complete the requeriments for your job application.
    Autogenerated by FlutLab FTF Generator
  */
class CompletetherequerimentsforyourjobapplicationWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Complete the requeriments for your job application.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
