import 'package:flutter/material.dart';

/* Rectangle E0 1
    Autogenerated by FlutLab FTF Generator
  */
class E01Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 34.0,
      height: 34.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/ed4a053208a9b3ae6670fef9ea2a4e1b68e06245.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/ed4a053208a9b3ae6670fef9ea2a4e1b68e06245.png",
          color: null,
          fit: BoxFit.cover,
          width: 34.0,
          height: 34.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
