import 'package:flutter/material.dart';

/* Text In order to verify your experience and provide a good service to all our user students, we want you to share your Linkdin profile with us. Please enter your a link to your profile.
    Autogenerated by FlutLab FTF Generator
  */
class InordertoverifyyourexperienceandprovideagoodservicetoallouruserstudentswewantyoutoshareyourLinkdinprofilewithusPleaseenteryouralinktoyourprofileWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''In order to verify your experience and provide a good service to all our user students, we want you to share your Linkdin profile with us. Please enter your a link to your profile.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
