import 'package:flutter/material.dart';

/* Rectangle LLK 1
    Autogenerated by FlutLab FTF Generator
  */
class LLK1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 39.0,
      height: 39.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/5bde8c4264aa000ddee4e8fbfe873d44b0a7b7e9.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/5bde8c4264aa000ddee4e8fbfe873d44b0a7b7e9.png",
          color: null,
          fit: BoxFit.cover,
          width: 39.0,
          height: 39.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
