import 'package:flutter/material.dart';

/* Rectangle M0 2
    Autogenerated by FlutLab FTF Generator
  */
class M02Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 34.0,
      height: 34.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/864a6e0a39fffbe224096894e53295086b541623.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/864a6e0a39fffbe224096894e53295086b541623.png",
          color: null,
          fit: BoxFit.cover,
          width: 34.0,
          height: 34.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
