import 'package:flutter/material.dart';

/* Rectangle Q0 2
    Autogenerated by FlutLab FTF Generator
  */
class Q02Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 34.0,
      height: 34.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/1f05b59fc2acd902aa93993cceb5b189d6b09893.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/1f05b59fc2acd902aa93993cceb5b189d6b09893.png",
          color: null,
          fit: BoxFit.cover,
          width: 34.0,
          height: 34.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
