import 'package:flutter/material.dart';

/* Text Yo can select several
    Autogenerated by FlutLab FTF Generator
  */
class YocanselectseveralWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Yo can select several''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Century Gothic',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 140, 140, 140),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
