import 'package:flutter/material.dart';

/* Rectangle BTH 1
    Autogenerated by FlutLab FTF Generator
  */
class BTH1Widget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 35.0,
      height: 35.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/6ddd152983161eb1683e9abc196947fe62aba762.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/6ddd152983161eb1683e9abc196947fe62aba762.png",
          color: null,
          fit: BoxFit.cover,
          width: 35.0,
          height: 35.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
