import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* RegularPolygon Polygon 7
    Autogenerated by FlutLab FTF Generator
  */
class Polygon7Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.00, 1.00, 0.00, 0.00, -1.00, -0.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Opacity(
          opacity: 0.8999999761581421,
          child: Container(
            width: 25.0,
            height: 25.0,
            child: SvgWidget(painters: [
              SvgPathPainter.fill()
                ..addPath(
                    'M10.7679 3C11.5377 1.66667 13.4623 1.66667 14.2321 3L21.5933 15.75C22.3631 17.0833 21.4008 18.75 19.8612 18.75L5.13878 18.75C3.59918 18.75 2.63693 17.0833 3.40673 15.75L10.7679 3Z')
                ..color = Color.fromARGB(255, 255, 255, 255),
            ]),
          ),
        ));
  }
}
