import 'package:flutter/material.dart';

/* Rectangle Rectangle 10
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle10Widget17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: null,
          height: null,
          decoration: BoxDecoration(
            color: Color.fromARGB(255, 245, 246, 250),
          ),
          child: null,
        ),
      ),
    );
  }
}
