import 'package:flutter/material.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle11Widget11.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/ReportyourproblemasWidget1.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle18Widget13.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/SendWidget4.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/ProfileWidget3.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Line2Widget7.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/MendezJimenezWidget3.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle31Widget1.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle13Widget16.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/BTC1Widget16.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle29Widget5.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/SD11Widget1.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Wetakecareofyourproblems247Widget2.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle12Widget16.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Polygon7Widget1.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Ellipse4Widget13.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle10Widget17.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/MoneyWidget1.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle30Widget3.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle16Widget16.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/AtthebeginningofthesessionthestudentappearswithanotherpersonviolatingtheTutoFastrulessharingthelinkofthesessionwithotherpeopleWidget.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Polygon6Widget1.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle9Widget17.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle25Widget6.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/PabloGabrielWidget3.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle8Widget18.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/Rectangle22Widget5.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/SettingsWidget3.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/SessionProblemsWidget1.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/StudentcommitspenaltyduringclassWidget.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/BTP1Widget16.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/ComplaintCenterWidget2.dart';
import 'package:flutterapp/figma/teachercomplaintcenterwidget/widgets/BTH1Widget16.dart';

/* Frame Teacher Complaint Center
    Autogenerated by FlutLab FTF Generator
  */
class TeacherComplaintCenterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: Rectangle10Widget17(),
          ),
          Positioned(
            left: 0.0,
            top: 717.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 94.0,
            child: Rectangle9Widget17(),
          ),
          Positioned(
            left: 45.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 41.0,
            height: 17.0,
            child: ProfileWidget3(),
          ),
          Positioned(
            left: 13.0,
            top: 728.0,
            right: null,
            bottom: null,
            width: 105.0,
            height: 27.9255313873291,
            child: Rectangle13Widget16(),
          ),
          Positioned(
            left: 284.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 52.0,
            height: 17.0,
            child: SettingsWidget3(),
          ),
          Positioned(
            left: 164.0,
            top: 733.0,
            right: null,
            bottom: null,
            width: 48.0,
            height: 17.0,
            child: MoneyWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 765.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 47.0,
            child: Rectangle8Widget18(),
          ),
          Positioned(
            left: 279.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTC1Widget16(),
          ),
          Positioned(
            left: 170.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: BTH1Widget16(),
          ),
          Positioned(
            left: 66.0,
            top: 770.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 35.0,
            child: BTP1Widget16(),
          ),
          Positioned(
            left: 61.0,
            top: 809.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 4.0,
            child: Rectangle12Widget16(),
          ),
          Positioned(
            left: 23.0,
            top: -15.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 125.0,
            child: Rectangle16Widget16(),
          ),
          Positioned(
            left: 92.0,
            top: 79.0,
            right: null,
            bottom: null,
            width: 191.0,
            height: 13.0,
            child: Wetakecareofyourproblems247Widget2(),
          ),
          Positioned(
            left: 23.0,
            top: 140.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 80.0,
            child: Rectangle11Widget11(),
          ),
          Positioned(
            left: 338.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: Polygon7Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 250.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 61.0,
            child: Rectangle22Widget5(),
          ),
          Positioned(
            left: 41.0,
            top: 291.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 0.0,
            child: Line2Widget7(),
          ),
          Positioned(
            left: 23.0,
            top: 341.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 168.0,
            child: Rectangle25Widget6(),
          ),
          Positioned(
            left: 23.0,
            top: 539.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 95.0,
            child: Rectangle31Widget1(),
          ),
          Positioned(
            left: 23.0,
            top: 539.0,
            right: null,
            bottom: null,
            width: 330.0,
            height: 95.0,
            child: Rectangle18Widget13(),
          ),
          Positioned(
            left: 186.0,
            top: 566.0,
            right: null,
            bottom: null,
            width: 101.0,
            height: 18.0,
            child: PabloGabrielWidget3(),
          ),
          Positioned(
            left: 165.0,
            top: 581.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 34.0,
            child: MendezJimenezWidget3(),
          ),
          Positioned(
            left: 41.0,
            top: 470.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 26.0,
            child: Rectangle30Widget3(),
          ),
          Positioned(
            left: 41.0,
            top: 357.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 101.0,
            child: Rectangle29Widget5(),
          ),
          Positioned(
            left: 86.0,
            top: 41.0,
            right: null,
            bottom: null,
            width: 207.0,
            height: 42.0,
            child: ComplaintCenterWidget2(),
          ),
          Positioned(
            left: 338.0,
            top: 286.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 20.0,
            child: Polygon6Widget1(),
          ),
          Positioned(
            left: 41.0,
            top: 270.0,
            right: null,
            bottom: null,
            width: 235.0,
            height: 16.0,
            child: StudentcommitspenaltyduringclassWidget(),
          ),
          Positioned(
            left: 168.0,
            top: 474.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 18.0,
            child: SendWidget4(),
          ),
          Positioned(
            left: 55.0,
            top: 371.0,
            right: null,
            bottom: null,
            width: 268.0,
            height: 60.0,
            child:
                AtthebeginningofthesessionthestudentappearswithanotherpersonviolatingtheTutoFastrulessharingthelinkofthesessionwithotherpeopleWidget(),
          ),
          Positioned(
            left: 133.0,
            top: 186.0,
            right: null,
            bottom: null,
            width: 174.0,
            height: 13.0,
            child: ReportyourproblemasWidget1(),
          ),
          Positioned(
            left: 133.0,
            top: 158.0,
            right: null,
            bottom: null,
            width: 147.0,
            height: 30.0,
            child: SessionProblemsWidget1(),
          ),
          Positioned(
            left: 69.0,
            top: 156.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 50.0,
            child: SD11Widget1(),
          ),
          Positioned(
            left: 45.0,
            top: 553.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 70.0,
            child: Ellipse4Widget13(),
          )
        ]),
      ),
    ));
  }
}
